### ISSUE TITLE
Option to switch repositories when there are multiple options

### ISSUE THREAD

**Issue by Boeller666** [komodorio/helm-dashboard#104]
I need an option to select the right repository to install from.

We have cert-manager installed via the jetstack helm repository, but I also have the bitnami repository which also includes a cert-manager chart. Everytime I look at the cert-manager deployment and would like to change something, I got only versions from bitnami repo and not jetstack.

**Comment by undera** [comment]
Thanks for reporting this @Boeller666 , this is indeed an issue. We'll see how can we address it.

**Comment by undera** [comment]
Alternatlively, we can update all potential repos and display all of them in the version list, grouped accordingly

**Comment by undera** [comment]
What I've added in #215 is the label inside version drop-down that will display the repository originating the version. It should resolve the ambiguity
