### ISSUE TITLE
Upon power-off performed, overlay with explanation

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#105]
In some situations, browser fails to close the tab on power off clicked.

In this case, let's overlay the whole screen with some meaningful explanation like "The server side of application has been shut down, you should close this browser tab now"

**Comment by professorabhay** [comment]
I am interested to work on this !!
Just need some little bit help as a beginner

**Comment by undera** [comment]
Hello,
The place where overlay display should be triggered is this one: https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/static/scripts.js#L221

Some bootstrap modal would serve the purpose.

**Comment by siddhikhapare** [comment]
@undera  I have tried to resolve this issue. Can you please check my PR once.  https://github.com/komodorio/helm-dashboard/pull/120
