### ISSUE TITLE
unknown flag `bind' in the v0.26

### ISSUE THREAD

**Issue by kenchen1101** [komodorio/helm-dashboard#112]
DEBU[0000] Got latest version from GH: v0.2.6
^C
[root@chartmuseum ~]# helm dashboard --no-browser  --verbose --bind=0.0.0.0
unknown flag `bind'
Error: plugin "dashboard" exited with error
[root@chartmuseum ~]# helm dashboard --no-browser  --verbose --bind 0.0.0.0
unknown flag `bind'
Error: plugin "dashboard" exited with error

**Comment by undera** [comment]
The `--bind` flag is introduced very recently and will be part of the next release. We're planning to do the release today/tomorrow.

**Comment by undera** [comment]
Sorry for the inconvenience.

**Comment by kenchen1101** [comment]
copy. thanks.
