### ISSUE TITLE
Helm dashboard doest not show pending and superseded releases

### ISSUE THREAD

**Issue by olegsu** [komodorio/helm-dashboard#114]
**Feature Request**
Looking on [ListInstalled](https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/subproc/data.go#L99) ,it seems that `pending` and `superseded` releases are not shown and there is no way to opt-in this.

**Comment by undera** [comment]
From Helm CLI (`helm ls --help`), I see `--all` flag is supposed to show all statuses: "show all releases without any filter applied". This is exactly what we use in our code.
Are you sure the issue really exists? I've been testing exactly this some time ago and I saw "pending" releases in the list.

**Comment by olegsu** [comment]
You are right, the `helm ls -A --all` will show all releases.
I think the reason is that the release was installed on non-default namespace and the flag to list all namespaces was not provided or shown as this was the first installed chart.
![image](https://user-images.githubusercontent.com/23185631/203815871-83df4bc3-7e25-4fe9-abf2-84d16b9089d2.png)

**Comment by undera** [comment]
Sorry, I'm a bit confused now. Is there an issue? If yes, what are the steps to reproduce it?

**Comment by undera** [comment]
Obsolete with 1.0 release
