### ISSUE TITLE
"Failed to find chart in repo" message appeared for local chart

### ISSUE THREAD

**Issue by olegsu** [komodorio/helm-dashboard#116]
**Reproduce**
1. Install chart from local file system `helm install .`
2. Open helm-dashboard
3. Message "Failed to find chart in repo" will appear 
![image](https://user-images.githubusercontent.com/23185631/203813085-f99d63fb-59a8-4e59-b6b2-09b5243d642b.png)
Related 

**Related**
UI - https://github.com/komodorio/helm-dashboard/blob/bedb356b02f5cb6cd861ad2f16db55d1c674b3a6/pkg/dashboard/static/actions.js#L21
The backend response 

```
[GIN] 2022/11/24 - 16:53:54 | 500 |   34.611458ms |       127.0.0.1 | GET      "/api/helm/repo/search?name=REDACTED"
Error #01: Error: no repositories configured
```

**Comment by undera** [comment]
Thanks for reporting!
