### ISSUE TITLE
Add value to enable debug logging inside cluster

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#142]
Into values.yaml add something that will set DEBUG=1 env variable for deployment container

**Comment by OmAximani0** [comment]
Hello @undera, Sir I want to contribute to this how do I get started ? can you please guide me ?

**Comment by undera** [comment]
Sure.
Value file is here: https://github.com/komodorio/helm-dashboard/blob/main/charts/helm-dashboard/values.yaml
Container template is here: https://github.com/komodorio/helm-dashboard/blob/main/charts/helm-dashboard/templates/deployment.yaml

There should be a flag in values, something like `debug: true`, to enable a block of setting container env variable of `DEBUG: 1`

**Comment by OmAximani0** [comment]
Thank you @undera sir, I'll check this out now

**Comment by itsmeArpit07** [comment]
@undera Hi! I am new to this community so can you please tell me which techstack are you working on so I can learn it and understand it better.

**Comment by Hrishi5111998** [comment]
@undera Hello sir, I am new this tech world just started learning java few months back. Want to contribute to open source community and learn about tech everyday. So please tell how can I contribute to this project. Please guide. Thanks you.
