### ISSUE TITLE
How to install and update offline

### ISSUE THREAD

**Issue by pptfz** [komodorio/helm-dashboard#144]
For some reason, my server's direct access to github.com is limited. I can only access it normally through the agent. May I ask how can I install or update it offline

**Comment by undera** [comment]
It's addressed here: https://github.com/komodorio/helm-dashboard#manual-installation

Since dashboard is just a binary, you can download it via browser and then run it. Let me know if you need more guidance.

**Comment by pptfz** [comment]
Ok, thank you very much.
