### ISSUE TITLE
Write unit tests for version 1.0

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#148]
We have a massive set of changes coming to Go backend in `features-1.0` branch. Running `make test` shows current unit test coverage. It is quite low at the moment and the goal is to bring it up to 60-80%. 

It's a good exercise for anyone willing to practice Golang programming. Don't go crazy, simplistic tests are better to maintain. We don't need all possible combinations covered, single happy flow is good for the start. Since the object model code is based on [Helm's codebase](https://github.com/helm/helm), it is expected that their practices of test fixtures might be used as example. 

If something is missing in the object model, like the ability to inject the dependencies - let's discuss and add.

The work should be split into individual PRs, using `features-1.0` as a base branch. The breakdown is:

- [ ] `api.go` - some methods are super-easy to cover, like static route serving
- [ ] `objects/kubectl.go` - looks the easiest among the logic
- [ ] `objects/releases.go` - own kind of test style 
- [ ] `objects/repos.go` -  - different kind of test style

Also, quite a bit of logic lives in `handlers`, it also needs UT coverage with fake `gin` contexts, quite doable.

**Comment by Michealajit** [comment]
Hey Sir I'm interested but I'm new to this ..

**Comment by undera** [comment]
You can write single tests for the code to practice. The static parts in `api.go` are quite easy to cover. You can take some article about `gin` unit tests to begin learning (random example: https://blog.canopas.com/golang-unit-tests-with-test-gin-context-80e1ac04adcd).

Coverage can be improved even by adding single test per PR. I will review and tell if it is ok, or something wrong.

**Comment by harish343** [comment]
hey how can I contribute here

**Comment by undera** [comment]
> hey how can I contribute here

Checkout the project, run unit tests for it and build the coverage report. Find a function that is not covered and add a test for it. Use existing tests as an example.
