### ISSUE TITLE
Feat: automate pull request labeling 

### ISSUE THREAD

**Issue by Niravprajapati1** [komodorio/helm-dashboard#152]
### Description

We can automate issue labeling like if any one open an issue then it automatically attach a label regarding to issue 
 

### Additional information

For this we can use github action

**Comment by undera** [comment]
Can you give an example? Which label in which situation would you add?

**Comment by Niravprajapati1** [comment]
You can checkout this actions https://github.com/actions/labeler

**Comment by undera** [comment]
That action mentions PR labeling, not issue labeling, if I read it correctly.

**Comment by Niravprajapati1** [comment]
Ya you are right my bad !!

**Comment by undera** [comment]
Feel free to create a PR with your idea of labeling configuration

**Comment by Niravprajapati1** [comment]
Thanks 👍

**Comment by hdm23061993** [comment]
@Niravprajapati1 
Do you mind if I pick this?

**Comment by Niravprajapati1** [comment]
@hdm23061993 you can work on this 🎉

**Comment by hdm23061993** [comment]
Thanks 🙏
