### ISSUE TITLE
`make test` not able to create cover profile

### ISSUE THREAD

**Issue by OmAximani0** [komodorio/helm-dashboard#156]
### Description

`make test` command should create a cover profile file to measure the coverage percentage but it is not able to

### Screenshots

![image](https://user-images.githubusercontent.com/75031769/210133864-e8ac92b5-6a38-4d0e-ad47-d14d9920fd71.png)

**Comment by OmAximani0** [comment]
I think file extension for profile should be `.out` since it is mentioned in gitignore
https://github.com/komodorio/helm-dashboard/blob/3e1e4be4b35102a04c74fd4213f5b64ecaf158f4/.gitignore#L16-L17

**Comment by undera** [comment]
IMO `.cov` is more meaningful. I've added it into gitignore
