### ISSUE TITLE
Change `action/checkout` version to `v3`

### ISSUE THREAD

**Issue by OmAximani0** [komodorio/helm-dashboard#159]
Since `action/checkout@v2` uses `Node 12.x.x` and it is [deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) I think we must use `action/checkout@v3`
https://github.com/komodorio/helm-dashboard/blob/3e1e4be4b35102a04c74fd4213f5b64ecaf158f4/.github/workflows/build.yml#L45-L50
https://github.com/komodorio/helm-dashboard/blob/3e1e4be4b35102a04c74fd4213f5b64ecaf158f4/.github/workflows/build.yml#L59-L63

**Comment by undera** [comment]
Feel free to create a PR against `main` branch

**Comment by OmAximani0** [comment]
ok sir
