### ISSUE TITLE
Is there anyway to use list the releases with out Cluster Role

### ISSUE THREAD

**Issue by vinaybabu84** [komodorio/helm-dashboard#189]
### Description

We don't want to get all releases from entire cluster level, which is strictly restricted. As we maintain around 100 namespaces, and we want to get releases from those namespaces, where we have admin roles on those namespaces.

I looked at what Kubectl queries and what helm commands the helm-dashboard is triggering as it is using --all-namespaces, which is resulting it into error.

time="2023-01-13T15:54:50Z" level=warning msg="Failed command: [kubectl get namespaces -o json]"
time="2023-01-13T15:54:50Z" level=warning msg="STDERR:\nError from server (Forbidden): namespaces is forbidden: User \"system:serviceaccount:hello-test-ns:helm-dashboard\" cannot list namespaces at the cluster scope: no RBAC policy matched\n"
[GIN] 2023/01/13 - 15:54:50 | 500 |  124.879512ms |   130.41.40.103 | GET      "/api/kube/namespaces"
Error #01: Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:hello-test-ns:helm-dashboard" cannot list namespaces at the cluster scope: no RBAC policy matched

[GIN] 2023/01/13 - 15:54:51 | 200 |    1.002217ms |   130.41.40.103 | GET      "/static/topographic.svg"
time="2023-01-13T15:54:51Z" level=warning msg="Failed command: [**helm ls --all --output json --time-format 2006-01-02T15:04:05Z07:00 --all-namespaces**]"
time="2023-01-13T15:54:51Z" level=warning msg="STDERR:\nError: list: **failed to list: secrets is forbidden: User \"system:serviceaccount:hello-test-ns:helm-dashboard**\" cannot list secrets at the cluster scope: no RBAC policy matched\n"
[GIN] 2023/01/13 - 15:54:51 | 500 |   53.348766ms |   130.41.40.103 | GET      "/api/helm/charts"
Error #01: Error: list: failed to list: secrets is forbidden: User "**system:serviceaccount:hello-test-ns:helm-dashboard**" cannot list secrets at the cluster scope: no RBAC policy matched

I have executed the same commands by replacing --all-namespaces with -n <namespace>, with that all those commands works.. is that anyway to pass specific namespace or list of namespaces

### Screenshots

![2023-01-13 11_28_04-Helm Dashboard](https://user-images.githubusercontent.com/122632497/212382082-a285f4b9-a887-4e27-8aeb-7d15ee9b96aa.png)

**Comment by vinaybabu84** [comment]
Is that something like this need to do helm upgrade --install my-release komodorio/helm-dashboard **--namespace=...** --set dashboard.allowWriteActions=true --set service.port=9090

**Comment by undera** [comment]
No, that command would only work if you use  helm-dashboard locally

**Comment by undera** [comment]
Actually it would be good to add to our Helm chart the value to control `--namespace` parameter of helm-dashboard.

**Comment by vinaybabu84** [comment]
That would be great add additional parameter in values.yaml to allow namespaces or even better to have added it environment variable

**Comment by undera** [comment]
The env variable is already there, it's called `HELM_NAMESPACE`

**Comment by vinaybabu84** [comment]
This is really amazing 
I added HELM_NAMESPACE and it works only with 1 namespace and when added 2 namespaces as **HELM_NAMESPACE: test-ns1 test-ns2** , it gives error. It takes as helm ls --all --output json --time-format 2006-01-02T15:04:05Z07:00 --namespace test-ns1 test-ns2.

How can we make it work for multiple namespaces?

Second the namespaces is showing error as attached.
![2023-01-13 16_29_12-Helm Dashboard_1](https://user-images.githubusercontent.com/122632497/212431381-54841dbc-3ea0-4da9-9fc1-f82f8bec1f09.png)

**Comment by undera** [comment]
This is how Helm itself works. It only allows specifying one namespace for its operations.

**Comment by kiranreddy97** [comment]
I ran into the same issue where it was working for only one namespace. Is there any way to pass multiple namespaces in values.yml or an env variable? I tried the following examples: app_test, app_QA, and app_test + app_QA, but it is not working.

I have access from one namespace to multiple namespaces. If it works for multiple spaces, it would be ideal if we could install Helm-Dash-Board in a single namespace and make it available to my entire cluster of projects .

**Comment by vinaybabu84** [comment]
Yes, exactly I felt the same.. we need to allow multiple namespace as we don't have permission to cluster. 

I installed and it allows only one namespace and also have error (Error from server(forebiden) namespaces is forebidden User... for cluster scope)
