### ISSUE TITLE
Its allowing only one namespace, where it needs to allow multiple namespaces with out cluster rol

### ISSUE THREAD

**Issue by vinaybabu84** [komodorio/helm-dashboard#193]
### Description

This tied to issue 189. it now allows one namespace to set. we need to have multiple namespaces to allow with out cluster role

**Comment by undera** [comment]
Just as I explained in issue #189, Helm internally only works either with all namespaces at once or with single namespace. There is no way to specify multiple namespaces for Helm.

**Comment by vinaybabu84** [comment]
Totally get that.

We need to have a way to supply multiple namespaces with out pulling all namespaces in a cluster(kubectl get namespaces -o json) and also UI should list all the supplied namespaces. Upon clicking the namespace in UI, it has to pass that namespace to helm command to list the releases.

This is very helpful Dashboard which we are planning to build since from long, since we have 500+ nodes in multiple datacenters and around 280 namespaces which are maintained by different teams we have strict policies where one team projects should not visible to other.

**Comment by undera** [comment]
I have committed support for multiple namespaces in #147 , will be part of 1.0 release

**Comment by kiranreddy97** [comment]
Deployed the latest version and still it fails with same error , is there any configuration or env variables required to pull multiple namespaces ?

Note i Just tried HELM_NAMESPACE = UAT , DEV 
HELM_NAMESPACE = UAT   DEV

**Comment by vinaybabu84** [comment]
![image](https://user-images.githubusercontent.com/122632497/214320218-06caea5b-5190-48cb-9efa-5dd543566236.png)

Saw you guys provide a capability to support multiple namespaces with out cluster role, but not sure how to pass the same from values.yaml?

**Comment by undera** [comment]
@kiranreddy97 @vinaybabu84 This feature will only be available after release 1.0

However, you can help the project by trying it out earlier than it is released, by checking out the source code of 1[features-1.0](https://github.com/komodorio/helm-dashboard/tree/features-1.0) branch, running `make build` and then testing `bin/dashboard` binary with your namespace options.

**Comment by vinaybabu84** [comment]
When is release 1.0 scheduled?
