### ISSUE TITLE
Error: unknown flag: --time-format while opening dashboard

### ISSUE THREAD

**Issue by dvdgitman** [komodorio/helm-dashboard#194]
### Description

My Helm3 version is 3.8.2 , I saw this issue happened on versions before 3.4.0 but I'm not at that version.
What to do?

### Screenshots

![Screenshot 2023-01-18 at 14 44 39](https://user-images.githubusercontent.com/5166585/213174901-0eac9bcd-30f5-4800-8e98-d7ecc55c1aab.png)

### Additional information

─❯ helm3 version
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

edit: I have 2 helm versions installed , Helm3 and helm ( helm2 ) 
And I saw that the commend is helm ls --all --output json --time-format 2006-01-02T15:04:05Z07:00 --all-namespaces --kube-context

is it possible to change it to helm3 ls? since this is the bin I have for changing between versions

**Comment by undera** [comment]
Hi,
Currently, there is no option to switch to other helm binary. you might try to use shell alias to temporarily switch it:
```shell
alias helm=helm3
helm version
helm dashboard
```

**Comment by undera** [comment]
The major release 1.0 that is in works now (#147) would not have this problem.

**Comment by dvdgitman** [comment]
Thanks!!
