### ISSUE TITLE
WSL2 support opening the default Windows browser

### ISSUE THREAD

**Issue by LarsBingBong** [komodorio/helm-dashboard#21]
Hi Komodor IO

I'm getting:

![image](https://user-images.githubusercontent.com/80959443/196898846-11498815-ebdb-42cd-819a-ccdbbab1774f.png)

Is it possible for the `plugin` here to open the default browser/figure out what it is and open it?

Thank you.

**Comment by undera** [comment]
Hey,
Thanks for reporting it.

Currently, we're using this library to autodetect and open the browser: https://github.com/toqueteos/webbrowser
Probably, that library is imperfect in Windows support.
I'll create a PR to try to migrate onto https://github.com/pkg/browser

Will you be able to test that version from the branch?

**Comment by undera** [comment]
Also, the issue might be because your WSL2 does not have `x-www-browser` configured. That's easy to check, just run `x-www-browser https://google.com` in your console.

**Comment by LarsBingBong** [comment]
Running `x-www-browser https://google.com` in `WSL2` works. The default Windows system browser opens up.

Yeah, if I can pull a branch from this repo where `pkg/browser` is used. Then yes.

**Comment by undera** [comment]
I have pushed the [fix/windows-browser](https://github.com/komodorio/helm-dashboard/tree/fix/windows-browser) branch. 

Please check it out and build locally to try (https://github.com/komodorio/helm-dashboard#local-dev-testing)

**Comment by undera** [comment]
I liked that library change anyway, it was having much less dependencies
