### ISSUE TITLE
Can't load information about a Helm release

### ISSUE THREAD

**Issue by nurayko** [komodorio/helm-dashboard#214]
### Description

Hi,
We have a release that is relatively big. Trying to open it through the dashboard results in error : 
[GIN] 2023/02/13 - 13:22:47 | 500 |    6.4350284s |       127.0.0.1 | GET      "/api/helm/releases/$namespace/$release-name/resources"
Error #01: failed to parse manifest document #195, cause: yaml: unmarshal errors:
  line 8068: mapping key "runAsNonRoot" already defined at line 8065

dashboard version info:
time="2023-02-13T13:22:07+02:00" level=info msg="Helm Dashboard by Komodor, version 1.0.0 (8faa5dabd59c1efa132de306a573b2922fedf873 @ 2023-02-01T16:03:40Z)"
time="2023-02-13T13:22:07+02:00" level=info msg="User analytics is collected to improve the quality, disable it with --no-analytics"
time="2023-02-13T13:22:07+02:00" level=info msg="Opening web UI: http://localhost:8080"

**Comment by undera** [comment]
That's exactly what it says. Your helm chart produces a manifest that does not contain a valid YAML. You can validate that by taking full manifest text and loading it into strict YAML parser. Strictly speaking, your templates should be fixed to not produce that duplicate `runAsNonRoot` key.

I was investigating this problem in #30, and found a corresponding Helm [issue](https://github.com/helm/helm/issues/5524), where they say that they don't aim to control the validity of resulting YAML manifests.

I understand that somehow k8s manages to accept and process these manifests, but I failed to find exact place in source code of k8s to maybe copy it.
