### ISSUE TITLE
Improve Helm chart to not fail on simple install

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#221]
When I install Helm chart, it fails to run the app because of PersistentVolume not specifying local directory. Disabling persistence still generates PVC (sic!)

We need to improve the chart to have a logic:

- when no values specified upon chart install, it should use an EmptyDir and just start
- when "hostPath" specified without storageClass, it would run fine just like today
- when specific storageClass is specified, it is respected
- it should allow changing the storageClass via chart reconfiguration

For the context, #206 were not fully good change, I experience different PVC-related failures after it.
Also https://github.com/komodorio/helm-charts/issues/146 is the context of realistic example.

**Comment by pat-nel87** [comment]
I'd be interested in taking a shot at this one.
