### ISSUE TITLE
Support password protected helm charts

### ISSUE THREAD

**Issue by zingz0r** [komodorio/helm-dashboard#222]
With the following cmd, you can add easily a protected repository to your charts.

`helm repo add chart-name https://private-repository.company.com --username <user>--password <pass>`

However, it's not possible through the helm-dashboard. 
Please consider adding this feature.

**Comment by undera** [comment]
This is a very meaningful request. It can be easily implemented, easy to contribute.

What needs to be done is:

1. Add "username" and "password" fields to the repository adding form
2. Make sure those fields are sent via JS to backend API
3. Change backend to accept the values and apply them to Helm (`repos.go`, `Repositories.Add()`)

**Comment by DevFaizann** [comment]
Thank you for sharing your solution code for adding a protected repository to the Helm dashboard. I see that it includes the username, password, and repository URL fields, which is great! I just wanted to confirm that we need to include all of these fields in the form to ensure that the backend API can execute the `helm repo add` command successfully. I really appreciate your contribution and look forward to working together on this feature.
The following code demonstrates how a protected repository shall be added to Helm using the `helm repo add` command:

```
# Define the repository URL and credentials
repo_url="https://example.com/charts"
username="my_username"
password="my_password"

# Add the repository to Helm
helm repo add my_repo $repo_url --username $username --password $password
```
- When the user submits the form, validate the inputs to ensure that all required fields are filled and that the URL is a valid repository URL.
- Also, send an AJAX request to the backend API with the form data and the Helm dashboard should verify that the repository can be accessed using the provided credentials. If the verification fails, the user should be notified of the error and prompted to re-enter their credentials.
- Moreover, check the output of the `helm repo add` command to verify that the repository has been added successfully, and return an appropriate response to the front end.
- Finally, the Helm dashboard should display a confirmation message to the user that the protected repository has been added successfully.

**Comment by hdm23061993** [comment]
@undera 
I would like to work on this

**Comment by undera** [comment]
Awesome! It's yours. 

Ask for any clarification needed.

**Comment by undera** [comment]
Any ETA on this @hdm23061993 ?

**Comment by hdm23061993** [comment]
Unfortunately i have not been able to work on this. Have some issues with the laptop.

You can reassign if its urgent

**Comment by hdm23061993** [comment]
I have created a draft PR
Please feel free to add changes to it
