### ISSUE TITLE
helm repo add chart-name https://private-repository.company.com --username <user>--password <pass>

### ISSUE THREAD

**Issue by ranjan2829** [komodorio/helm-dashboard#223]
### Description

> With the following cmd, you can add easily a protected repository to your charts.
> 
> `helm repo add chart-name https://private-repository.company.com --username <user>--password <pass>`
> 
> However, it's not possible through the helm-dashboard. Please consider adding this feature.

**Comment by undera** [comment]
It's a duplicate of #222
