### ISSUE TITLE
Failed to scan resources error

### ISSUE THREAD

**Issue by jscharber** [komodorio/helm-dashboard#227]
### Description

Running a scan results in multiple targets cannot be specified.

This appears to be an issue with trivy, see the link below

https://github.com/aquasecurity/trivy/issues/934

```
labels:
    helm.sh/chart: helm-dashboard-0.1.5
```
![image](https://user-images.githubusercontent.com/1690714/222990051-26fb0396-cd12-473b-9733-bbf7394fa109.png)

**Comment by undera** [comment]
Helm dashboard is not using `--skip-dirs` option of Trivy, so I doubt it's the same issue.

I have Trivy version `0.38.1` and it works fine for me. Can you please tell me the version of Trivy you have installed, and also run dashboard with `-v` parameter to print the exact failed command into log. Then post here what were the command that it tried to run and failed.

**Comment by undera** [comment]
Scan functionality gets dropped completely from V2
