### ISSUE TITLE
Support local chart installing

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#23]
We need to address a case when user has local Helm chart and wants to enjoy the preview of manifests. 
Probably it should be analogous to chart repositories.

**Comment by ahaw023** [comment]
i would add something to do this

we use terraform to deploy a lot of our charts so a devops engineer may not have the repos locally

it would be great if the message said something like .. you do not have the helm repo added to allow us to evaluate new versions... please add the repo by running helm repo add xxxxx
