### ISSUE TITLE
UI - General - Modal Popup

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#243]
### What do you need to do?
Create an empty global modal. 

### Requirements

- [ ] Track multiple open modals.
- [ ] Allow other developers to configure modal 

Modals should follow this basic layout.
The top bar should be reserved for a title and close modal button (X).
The middle section should expand according to the content displayed up to the size of 500px after that a scroll wheel should appear.
The lower bar should be used for action buttons such as approve or cancel.

![Image](https://user-images.githubusercontent.com/127234894/224653780-2b650d0c-a8e8-45a6-9c5d-19fdffc173e4.png)

### References to help you get started
https://flowbite.com/docs/components/modal/
https://tailwindui.com/components/application-ui/overlays/modals

**Comment by ErezBiren** [comment]
Hi,
Was the React project already published?
I would love to take this task.

**Comment by chad11111** [comment]
@ErezBiren Hey! Perfect.
I would suggest reading the readme.md and launching the legacy dashboard, playing around a bit with the modals.

Open a PR when you feel like you are ready for a code review (this can even but during development).

**Comment by ErezBiren** [comment]
@chad11111 
Great! 
Thanks

**Comment by ErezBiren** [comment]
Should I be assigned?

**Comment by chad11111** [comment]
> Should I be assigned?

your assigned

**Comment by ErezBiren** [comment]
I'm not sure what does it mean:
"Track multiple open modals."
