### ISSUE TITLE
UI - Installed page

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#245]
The installed page has two views.

First is the installed charts page

![Image](https://user-images.githubusercontent.com/127234894/224651828-8ddd4568-1a65-421f-bad2-b322ffab70bc.png)

Second is the chart view

![Image](https://user-images.githubusercontent.com/127234894/224651947-f4210a28-6c6d-4c1e-b209-2a11c99abebe.png)

**Comment by kabhamo** [comment]
@chad11111, I would like to take this issue on my own.
Can you assign it to me, please?

**Comment by ErezBiren** [comment]
@chad11111 
I would love to take this one.

**Comment by chad11111** [comment]
@ErezBiren you got it sir! your gonna become the MVP of this project.

**Comment by ErezBiren** [comment]
Thank you :)
