### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#248]
- [ ] Error modal
- [ ] Describe modal
- [ ] Confirm modal
- [ ] Repo add modal
- [ ] Upgrade modal
- [ ] Test modal
- [ ] Power off modal

**Comment by Pravesh-Sudha** [comment]
I would like to work on it but I don't know react. Can I contribute while learning?

**Comment by zivnadel** [comment]
I would like to work on this.

**Comment by chad11111** [comment]
@zivnadel what modal do u want to develop ?

**Comment by zivnadel** [comment]
Error and Confirm modals. Is there a set of styles more precise than the general modal style in the storybook? Copy from the old version?

**Comment by zivnadel** [comment]
@chad11111

**Comment by chad11111** [comment]
@zivnadel the models are developed but not implemented (meaning they don't work) you can start making them work (open in the correct spaces, have a look at the old dashboard)
