### ISSUE TITLE
UI - General - Page layout

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#251]
Construct the skeleton for application pages, this should include a header and content body.

![Image](https://user-images.githubusercontent.com/127234894/224655020-1e94c6f1-1082-4f25-a47b-fa0bbb5f4441.png)

**Comment by aman1376** [comment]
i would like to work on this

**Comment by chad11111** [comment]
@aman1376 hey please note.

Dont work on the components but only on the layout.

**Comment by chad11111** [comment]
@aman1376 Do you understand the concept behind this task?

**Comment by aman1376** [comment]
I need to create the dashboard layout. So basically how  the header should be placed the different parts in it, then  there needs to be a body with different holder for all the components
