### ISSUE TITLE
Make "Back" button to work

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#26]
Find out how to make navigation to remember the hash history and reload page on clicking Back.

**Comment by ahaw023** [comment]
also on the overview UI it would be good to get proper HTML anchor tags so you can open up a new tab to look at a chart quickly and return to the overview screen

The current rendering process slows things down

![image](https://user-images.githubusercontent.com/106289240/198511934-d7ca66e5-0082-44f8-8c04-e7d765892af4.png)

**Comment by undera** [comment]
Fixed in V2
