### ISSUE TITLE
UI - General - Shutdown modal

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#260]
This modal can be located by pressing the shutdown button in the tool bar.

![Image](https://user-images.githubusercontent.com/127234894/225098584-13db9207-59f0-4307-bb23-108e3a31ad14.png)

It should look like this

![Image](https://user-images.githubusercontent.com/127234894/225098409-8348827a-c0b7-4b74-a96f-82ca54406f89.png)

**Comment by ofirlevy6658** [comment]
Hey, I'm interested in working on this issue

**Comment by aman1376** [comment]
@chad11111 i would like to work on this.

**Comment by chad11111** [comment]
@aman1376 thx! its urs

**Comment by pushker001** [comment]
Hey, @chad11111 I also want to work on this issue can I work on this issue?

**Comment by Lalman888** [comment]
is this issue relsoved ? I wanted to work on this

**Comment by MosheOgalbo** [comment]
@chad11111 

I would love to accept this assignment

**Comment by Lalman888** [comment]
@chad11111 Hey I would like to work on this

**Comment by MosheOgalbo** [comment]
Unable to push

**Comment by Lalman888** [comment]
@MosheOgalbo  Can you share error you getting

**Comment by MosheOgalbo** [comment]
remote: Permission to komodorio/helm-dashboard.git denied to MosheOgalbo.
fatal: unable to access 'https://github.com/komodorio/helm-dashboard.git/': The requested URL returned error: 403

**Comment by Lalman888** [comment]
Are you pushing directly or did you make fork than new branch?

**Comment by MosheOgalbo** [comment]
@Lalman888 
I'm pushing to the /helm-dashboard-v2/ branch

**Comment by Lalman888** [comment]
@MosheOgalbo  You have to follow these steps you have to fork this repo then clone then make new branch after that do changes then push in your branch then open new pull request.
You can just copy paste changes you have done

**Comment by MosheOgalbo** [comment]
@Lalman888 
remote: Permission to komodorio/helm-dashboard.git denied to MosheOgalbo.
fatal: unable to access 'https://github.com/komodorio/helm-dashboard.git/': The requested URL returned error: 403

**Comment by chad11111** [comment]
you need to 
1. fork
2. create a branch on your fork
3. make and commit changes to the branch
4. push the branch to YOUR fork
5. open a pull request from YOUR BRANCH TO THIS PROJECT
