### ISSUE TITLE
UI - General - Error Modal

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#261]
![Image](https://user-images.githubusercontent.com/127234894/225098819-c9f3fdf7-8e7e-44c6-9dd6-456d13e1b444.png)

**Comment by ErezBiren** [comment]
Hi @chad11111
I'll be glad to take this one

**Comment by Pravesh-Sudha** [comment]
Can I Work on this Issue

**Comment by YossiMorgen** [comment]
i'd like to do that
