### ISSUE TITLE
UI - Toolbar - help menu

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#263]
Reference html - https://github.com/komodorio/helm-dashboard/blob/47dae4d35a66b668e370d7cbf10a184a4133c329/pkg/dashboard/static/index.html#L39

![Image](https://user-images.githubusercontent.com/127234894/225104628-ebe26618-132d-403e-af25-e01530898723.png)

**Comment by abhinav2712** [comment]
@chad11111  Hello, as an UI/UX designer for many of the projects, I can develop this help menu way better, please assign me this issue, Thank you..

**Comment by chad11111** [comment]
@abhinav2712 Currently this is out of our project scope at the moment, if anything changes I will keep you in mind and update you.
Thank you for your offer! it's very much appreciated.

**Comment by hdm23061993** [comment]
@chad11111 I would like to work on this
What is expected from this issue?

**Comment by YossiMorgen** [comment]
i'd like to take this assignment too

**Comment by mridul037** [comment]
@chad11111  I would like to contribute to this issue please let me know ? requirements ?
