### ISSUE TITLE
UI - ToolBar - upgrade button

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#264]
Reference - https://github.com/komodorio/helm-dashboard/blob/57d4d073e9c4a3fb67677edb4ee2304381fed295/pkg/dashboard/static/index.html#L72

![Image](https://user-images.githubusercontent.com/127234894/225105549-c112c323-69b9-48ec-a8ca-b72b21bd7607.png)

**Comment by Pravesh-Sudha** [comment]
Can i Work on this issue

**Comment by Pravesh-Sudha** [comment]
What I have to do with this Button like move it in bottom or center or change its appearance

**Comment by chad11111** [comment]
@Pravesh-Sudha please make sure you don't open prs into main.
But instead `helm-dashboard-v2`. Thanks!

**Comment by mridul037** [comment]
hi @chad11111 I want to work on this

**Comment by AKACHI-4** [comment]
Hey is it open ?? can I work on it ..

**Comment by AKACHI-4** [comment]
Hey I want to work on this issue. Can you assign it to me

**Comment by Vishrut19** [comment]
Hey, can I work on this issue??

**Comment by shashank-mishra14** [comment]
Hey, the issues seems to be still opened. Assign it to me it looks easily solvable.

**Comment by Vishrut19** [comment]
Hey @chad11111! Please assign me this issue

**Comment by ErezBiren** [comment]
Already been implemented and merged.

**Comment by undera** [comment]
Why this issue is reopened then? @chad11111
