### ISSUE TITLE
Bug - Header isnt fixed

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#276]
### Description

The header must be fixed and not move if the body scrolls.
Also, the body should by default be the max height of the page and not overflow.

### Screenshots

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/127234894/226152180-c5196a11-6c5c-4e64-8281-0e9862670e25.png">

**Comment by Varnit-20** [comment]
Hey!
Can I work on this issue?

**Comment by hdm23061993** [comment]
@chad11111 
are we good to close this?

**Comment by chad11111** [comment]
@hdm23061993 yes
