### ISSUE TITLE
Add drop-down to namespace input

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#28]
In the Install dialog, offer existing namespaces in drop-down. Keep the ability to enter arbitrary namespace.

**Comment by Wyfy0107** [comment]
Hello can I work on this one ?

**Comment by undera** [comment]
Hey,
Yes, sure, you can take this one. If you need any guidance - ask me.

**Comment by Wyfy0107** [comment]
Not sure which bootstrap component should I use for this, that combine input and select into one. There's native html `datalist` but that does not look really nice

**Comment by undera** [comment]
I would use https://getbootstrap.com/docs/5.2/components/dropdowns/#methods
