### ISSUE TITLE
Infrastructure - header

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#282]
A layout page including header with logo and navigation tabs (Installed, Repository, Help dropdown, upgrade, shutdown). Including a shutdown button that closes the CLI process.
- On Success/Error the user will see a dialog with the operation status message
    - Including “upgrade button” for upgrading the helm chart package manager – the button will display the latest 
       version, clicking on it will lead to the GitHub repository
- Including Komodor logos
- The help dropdown will display a menu consisting the following items
  - Slack support chat – external link
  - Project page – external link
  - Reset cache – will invoke an operation of deleting the cache
  - REST API – external link
  - Current version number
- Shutdown button, which should open the shutdown dialog.

![Image](https://user-images.githubusercontent.com/127234894/226766228-b250af92-81a4-451a-ae1c-b26add0961cf.png)

**Comment by ErezBiren** [comment]
@chad11111  I would love to take this :)
