### ISSUE TITLE
Infrastructure - helm experience link

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#283]
When clicked should lead tovhttps://komodor.com/helm-dash/

![Image](https://user-images.githubusercontent.com/127234894/226767169-9bbb66a1-5856-4e18-abbf-2f4db4ac766f.png)

**Comment by ErezBiren** [comment]
@chad11111  I would love to take this.

**Comment by ErezBiren** [comment]
Fixed in #303
