### ISSUE TITLE
Infrastructure - help menu

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#284]
The help drop-down menu should contain:
- Chat support
- Project page
- Reset API
- rest API
- version indicator

![Image](https://user-images.githubusercontent.com/127234894/226766505-2fe09e8d-825e-4011-b182-8216a159d506.png)

**Comment by ErezBiren** [comment]
@chad11111  I would love to take this.

**Comment by ErezBiren** [comment]
Fixed in #302
