### ISSUE TITLE
Repository page - Repositories control

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#287]
A list of clusters where the users can choose one with radio buttons (this is an upgrade to the current system, please verify)

An “add repository” button - that opens the add repository modal

![Image](https://user-images.githubusercontent.com/127234894/226778361-9dc262a7-0595-41b7-9992-05e127e8cec4.png)

![Image](https://user-images.githubusercontent.com/127234894/226778431-dc523ae6-2841-4c83-bf2f-38e26c28f026.png)

**Comment by aman1376** [comment]
@chad11111 i would like to work on it

**Comment by ErezBiren** [comment]
I would take it @chad11111
