### ISSUE TITLE
Repository Page - Repository view

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#288]
Displaying relevant content for a selected repository
- Top section
    - Repo title
§  - Repo URL (clickable, will open in a new tab)
§  - Update button for fetching version updates
§  - Remove button to remove from the repo
§  - A filter text input to filter the displayed data
-  Bottom section
    - A table with “chat”, “description” and “version” columns (with two more columns that will be decided later on)
    - Hover on each row will display an “install” button for installing the version
   	- In case the repo is already installed the button will be disabled and will show tooltip on hover
  	- Installation status – is it installed or not, if installed show which version
-  Clicking on the status will lead the user to the installation page

![Image](https://user-images.githubusercontent.com/127234894/226778656-96d75d3e-d57d-4abd-87b5-39680b6d224c.png)

**Comment by MosheOgalbo** [comment]
@chad11111 
I would like to take this :)

**Comment by aman1376** [comment]
i was busy with some work so i wasnt able to complete the task. i am working on it now

**Comment by chad11111** [comment]
@aman1376 still? can u open a pr
