### ISSUE TITLE
Installed page

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#289]
- Clusters list like in the repositories page
- Table of the installed charts on the clusters and namespaces selected

![Image](https://user-images.githubusercontent.com/127234894/226792160-05f5613d-5251-412c-9bab-8b06abc4084b.png)

**Comment by ErezBiren** [comment]
@chad11111 
I can take it

**Comment by MosheOgalbo** [comment]
@chad11111 

Is it possible to take the execution of this task?

**Comment by MosheOgalbo** [comment]
@ErezBiren @chad11111 

Can I get this task?

**Comment by chad11111** [comment]
> @ErezBiren @chad11111
> 
> Can I get this task?

@MosheOgalbo this task has been completed by @ErezBiren 

@MosheOgalbo ill open some tasks for u soon

**Comment by hdm23061993** [comment]
I see this is completed
@chad11111  can we close this?
