### ISSUE TITLE
Installed page - Clusters list

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#290]
- Clusters list like in the repositories page
- Namespaces filters (using checkbox)

![Image](https://user-images.githubusercontent.com/127234894/226795291-a0e0c55b-30a5-41cb-91a2-5b5813a88aef.png)

**Comment by ErezBiren** [comment]
Hi @chad11111  
I would love to take this one.

**Comment by ErezBiren** [comment]
Fixed in #305

**Comment by chad11111** [comment]
@ErezBiren Its not visible yet :)

**Comment by MosheOgalbo** [comment]
@chad11111  @ErezBiren 

Can I get this task?
