### ISSUE TITLE
Installed page - Installed Charts

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#291]
Table of the installed charts on the clusters and namespaces selected
- Table title
- Table filter (text input)
- Columns: name, release status, chart, revision, namespace, updated
- Logo will be displayed similar to the current system
- Details
    - Name – will display the name of the chart and its description
       	If the user doesn’t have the latest version installed they will see some indication (icon) next to the name
    -  Status will display if a chart is installed or not – a chart installed is called “release”
    -  Chart – will display the chart version
    -  Revision
- Clicking on a release (row) will navigate the user to a page about it, similar to the repository page.

![Image](https://user-images.githubusercontent.com/127234894/226797373-1c5851c8-3cd8-46d3-9db3-537424bf8203.png)

**Comment by chad11111** [comment]
@YossiMorgen Thanks! assigned you.

**Comment by YossiMorgen** [comment]
Can i get the Package model?

**Comment by YossiMorgen** [comment]
and some more details like where am i supposed to get those from?
work with props or context or redux?

**Comment by YossiMorgen** [comment]
do you have the install's header svg?

**Comment by chad11111** [comment]
@YossiMorgen your first PR can just be the styles.

implement the props

state can be done later
