### ISSUE TITLE
Revisions page - Revision list

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#293]
Revisions list – this will display the evolution to deployed versions (including status, number of revisions,s and their age – e.g. 3m ago, hovering on the age will display a tooltip with the relevant date)

- In case of an upgrade or downgrade, the user will be able to see the old version and the new version numbers as well as an icon indication for upgrade/downgrade
- In case of a rollback the item will display an indicator icon for that, on hover, it will display a tooltip with the rollback revision number
- Clicking on any item will show the relevant revision information and will indicate which item is currently active

![Image](https://user-images.githubusercontent.com/127234894/226799734-6ed8bbef-519b-42d6-9238-bf84b72baa4f.png)

**Comment by EfratApter** [comment]
I would like to take this :)
