### ISSUE TITLE
Revisions page - Revision details

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#294]
Deployment status
-   Chart name
-   Chart revision and date
-   Tags: chart version, app version, namespace and cluster
-   Install status (the message from helm)
-   Action buttons: reconfigure, uninstall, check for new version
      -  Uninstall will display a confirmation popup with the details (what the user is deleting and from where and which objects will  
           be deleted) and confirm button
      -  Reconfigure – Will open a dialog where the users can:
   	   - Choose which version to install (from a dropdown)
   	   - View which version is currently installed, release name, namespace
   	   - View the cluster that the chart is installed on
   	   - View and edit the user-defined values in a textbox, on every edit (using debounce) the system will calculate and display 
                  the changes under “manifest changes” area
            -   in case of an error the user will see details about it
            -   in case of success the user will see side by side the YAML changes
   	        - View the chart values reference
   	        - Action buttons – scan for problem and confirm
         -   The reconfigure button will be displayed only if the user have the latest version installed, in case there isn’t they will see 
                 “upgrade to <version_number>” button instead
         -  Check for new version button will check if there is a new version available and will change the “reconfigure” button to the 
               “upgrade” button

Suggestion: We can auto-check for new version on every time interval and remove this button

![Image](https://user-images.githubusercontent.com/127234894/226803881-591cacba-db26-4681-8fff-1b7248409f76.png)

**Comment by ErezBiren** [comment]
@chad11111 
I would love to take this one.
