### ISSUE TITLE
Revisions Page - Tabs - Resources

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#295]
Resources; show a table of relevant resources – columns: Resource type, name, status, status message,
    - Each row will have two action buttons: Describe and Scan
           - Describe is showing a report from JSON object
           - Scan will invoke the scanner tool and show its status in a dedicate window/modal

**Comment by chad11111** [comment]
![Image](https://user-images.githubusercontent.com/127234894/226804612-20ad912a-cc5c-4fa9-8bf0-a0e70d604fc8.png)

**Comment by chad11111** [comment]
@YossiMorgen Thanks! assigned you

**Comment by chad11111** [comment]
@YossiMorgen are u doing this ?

**Comment by YossiMorgen** [comment]
Yes, I'm just waiting to see if you merge my first PR so it won't be a problem to merge my other changes
