### ISSUE TITLE
Revisions Page - Tabs - Values

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#297]
Users will be able to see the configuration file (YAML), diff with the previous one or from a selected revision (number input)
   	- The users will be able to select to see only the user-defined changes by a toggle button

![Image](https://user-images.githubusercontent.com/127234894/226804843-4c79fadf-19ad-4ead-a1cf-a1af253b6ff9.png)

**Comment by ErezBiren** [comment]
@chad11111 
I would love to take this one.
