### ISSUE TITLE
Shut down modal not popping up

### ISSUE THREAD

**Issue by aman1376** [komodorio/helm-dashboard#313]
### Description

On clicking the shut down button in the header a modal should have popped up but it's not happening. The modal pops up if we remove these lines // await axios
    //   .delete("/",)
    //   .then(() => {
    //     setSignOut(true);
    //     window.close();
    //   })
    //   .catch((error) => {
    //     console.error(error);
    //   });

### Screenshots

![Screenshot (58)](https://user-images.githubusercontent.com/96187306/229478499-707ed566-96f3-4e30-9cb7-a0a007746ce2.png)

### Additional information

When issue #307 was merged this issue arose as there was modification in the shutdownbutton.tsx file.

**Comment by hdm23061993** [comment]
Why do you need a popUp for shutdown? 
Is it for confirmation?

**Comment by undera** [comment]
Since the app becomes not operational after shutdown, we need to show this final popup explaining the situation and suggesting to close browser tab. We are trying to close the browser tab automatically, but that is not guaranteed for all browsers.

**Comment by hdm23061993** [comment]
I checked and the issue is because the API development is still in progress on `helm-dashboard-v2` branch. I see a PR open for it #334 
@ErezBiren

**Comment by shraddha761** [comment]
Can I work on this issue
