### ISSUE TITLE
Got "blocked by CORS policy" when trying to fetch data from helm-dashboard React

### ISSUE THREAD

**Issue by ErezBiren** [komodorio/helm-dashboard#314]
### Description

I'm having trouble fetching the status data
to the React client that runs on `http://localhost:5173/`
from the API in: `http://localhost:8080/status`
I think that some changes regarding CORS should be made on the server side.
This is the error I get:
`Access to fetch at 'http://localhost:8080/status' from origin 'http://localhost:5173/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. (edited)`

@chad11111

**Comment by KumarDhananjaya** [comment]
I would like to work on this !! Assign it to me

**Comment by undera** [comment]
This was addressed long time ago with env variable
