### ISSUE TITLE
Unable to retrieve local repo information: exit status 1

### ISSUE THREAD

**Issue by reto88** [komodorio/helm-dashboard#316]
### Description

When I run  helm plugin install https://github.com/komodorio/helm-dashboard.git i got the error Unable to retrieve local repo information: exit status 1
Why?
When I run helm list --all-namespaces then I see the charts

**Comment by undera** [comment]
This is the most likely reason: https://stackoverflow.com/questions/68982845/fail-to-install-helm-diff
It means that maybe some directory in your plugin cache prevents you from installing it. Try to clear that and repeat.

**Comment by reto88** [comment]
where can i find this folder on windows?

**Comment by reto88** [comment]
`helm plugin install https://github.com/databus23/helm-diff --version master` I can install, is only a problem with ` helm plugin install https://github.com/komodorio/helm-dashboard.git`

**Comment by undera** [comment]
I have an alternative suggestion: just download the Windows binary from releases page and run it. The plugin is just a wrapper that launches that binary. You can go to page https://github.com/komodorio/helm-dashboard/releases and download a file that ends with `_windows_x86_64.tar.gz`, unpack the archive and run `.exe` file inside. Should work.

**Comment by reto88** [comment]
unfortunately this is also not working. hmm

**Comment by undera** [comment]
That would be the primary problem to resolve. What does you observe? What exactly does not work?

**Comment by reto88** [comment]
so if i start the exe, the cmd pops up, but too fast to see anything, but the dashboard page is not starting, like if i could type `helm dashboard`

**Comment by reto88** [comment]
ah now it is working, with the exe, the problem was, that the port was already occupied.
