### ISSUE TITLE
Version to install options should be sorted semantically

### ISSUE THREAD

**Issue by martinwang2002** [komodorio/helm-dashboard#326]
### Description

Version to install options should be sorted semantically. It does not make sense for `argocd @ 5.2.0` to come before `argocd @ 5.19`.

### Screenshots

![image](https://user-images.githubusercontent.com/29770303/230893053-37a81cb9-58d1-4836-905c-c7748f8192a9.png)

### Additional information

https://github.com/komodorio/helm-dashboard/blob/a0bf59edc63e0a192896d7be1c63f7793e3bf6dc/pkg/dashboard/static/actions.js#L94

I don't think this line is necessary in terms of the api response for `/api/helm/repositories/versions?name=` as it's already sorted semantically.

**Comment by undera** [comment]
There is no guarantee that backend will provide the desired sorting. I believe the frontend should sort the list properly.
If anyone can fix that - contribution is welcome.

**Comment by harsh-anand22** [comment]
import re

def semver_sort(versions):
    def split_version(v):
        match = re.match(r'^(\d+)\.(\d+)\.(\d+)$', v)
        if match:
            return (int(match.group(1)), int(match.group(2)), int(match.group(3)))
        else:
            return None
    
    def semver_key(v):
        version_parts = split_version(v)
        if version_parts:
            return (version_parts[0], version_parts[1], version_parts[2])
        else:
            return (0, 0, 0)
    
    return sorted(versions, key=semver_key)

# Example usage
versions = ['5.2.0', '5.1.0', '5.19.0', '5.3.0', '5.18.0', '6.0.0']
sorted_versions = semver_sort(versions)
print(sorted_versions)

**Comment by undera** [comment]
That code is for backend, while I talk about frontend ensuring the sorting.

**Comment by undera** [comment]
@harshit-mehtaa This change actually broke it.
I now get whenever I try to click "reconfigure" button...
```actions.js:94 Uncaught TypeError: a.split is not a function
    at actions.js:94:37
    at Array.map (<anonymous>)
    at Object.<anonymous> (actions.js:94:25)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery-3.6.0.min.js:2:82355)
(```

**Comment by harshit-mehtaa** [comment]
Weird, I had tested it locally. Unfortunately missed to attach the screen shot in the PR
For the interim, can we revert the commit and merge it?

**Comment by undera** [comment]
Can we fix it instead? Make sure the parsing do not fail.

**Comment by harshit-mehtaa** [comment]
I have tried this

![image](https://user-images.githubusercontent.com/17697790/235184022-7fa74109-49bb-4ce3-bcad-acc75c2bf4dd.png)
