### ISSUE TITLE
some typos in README.md

### ISSUE THREAD

**Issue by KashishLakhara04** [komodorio/helm-dashboard#339]
### Description

I was going through the readme file and found two typos in it.
* Under **Description** section, the sentence should be:
This project is part of Komodor's vision of helping Kubernetes users to navigate and troubleshoot their clusters, the project is **NOT** an `official` project by the helm team.

*  Under **Support for Local Charts** section, the sentence should be:
For all the above use-cases, you may use Helm Dashboard UI, `specifying the` location of your local chart folders via special --local-chart command-line parameter. The parameter might be specified multiple times, for example:

### Screenshots

* ![fix1](https://user-images.githubusercontent.com/104296574/232233269-a153f9ab-812c-4ac3-b61e-4c8bd593e143.png)

* ![fix2](https://user-images.githubusercontent.com/104296574/232233280-3fdc0151-91eb-46d8-87f5-b96d5cf4374c.png)

**Comment by nati-elmaliach** [comment]
I would like to work on it :)
