### ISSUE TITLE
Make GH Actions step to validate the tag name matches the plugin.yaml

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#34]
To avoid broken releases

**Comment by ADITYADAS1999** [comment]
hey [Andrey Pokhilko](https://github.com/undera) this issue is still open ?

**Comment by undera** [comment]
Yes, it is still open.
It assumes a step in `release.yaml` that will check that plugin.yaml version matches tag name.

**Comment by ADITYADAS1999** [comment]
So, The action outputs plugin.yaml version as PACKAGE_VERSION and the tag (without 'refs/tags/') as TAG_NAME 🤔

**Comment by ADITYADAS1999** [comment]
> No, we can't generate `plugin.yaml` by action. The validation step is a safety valve that just checks that content of a certain field inside `plugin.yaml` matches `github.ref_name`

okey got this 💁🏻‍♂️
