### ISSUE TITLE
Installed charts - check resource health status

### ISSUE THREAD

**Issue by chad11111** [komodorio/helm-dashboard#357]
Currently it looks like this:
 
![Image](https://user-images.githubusercontent.com/127234894/240741029-1677d66d-876d-4ed4-bf03-5d705109235e.png)

We need are missing the green status bars:

![Image](https://user-images.githubusercontent.com/127234894/240741178-360d85a8-7109-4c2d-abc5-52606310a4b6.png)

The original source code can be found here.

**Comment by undera** [comment]
I don't see any recent source code pushes. Will you create a new PR?
