### ISSUE TITLE
Support acr protocol

### ISSUE THREAD

**Issue by clcc2019** [komodorio/helm-dashboard#360]
### Description

could not create repository object, cause: could not find protocol handler for: acr

**Comment by undera** [comment]
Can you provide more context on what you did exactly?

I also found this issue with some info on acr usage with Helm: https://github.com/helm/helm/issues/8094

**Comment by clcc2019** [comment]
I have a warehouse using the acr protocol. I added this warehouse information to my helm, and I can use the helm dashboard to view the warehouse information. But I deployed the helm dashboard chart to the cluster, he does not have my warehouse information, now I want to add this warehouse prompt does not support the acr protocol
<img width="286" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/cfa80d9a-8c68-45d3-aa5e-f0d897af4ef9">

**Comment by clcc2019** [comment]
> Can you provide more context on what you did exactly?
> 
> I also found this issue with some info on acr usage with Helm: [helm/helm#8094](https://github.com/helm/helm/issues/8094)

I have a warehouse using the acr protocol. I added this warehouse information to my helm, and I can use the helm dashboard to view the warehouse information. But I deployed the helm dashboard chart to the cluster, he does not have my warehouse information, now I want to add this warehouse prompt does not support the acr protocol
image
<img width="939" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/2e290972-4599-478e-ba84-e1515ff969ef">

**Comment by undera** [comment]
Try replacing `acr://` with `oci://`, according to the issue https://github.com/helm/helm/issues/8094 I mentioned

**Comment by clcc2019** [comment]
> Try replacing `acr://` with `oci://`, according to the issue [helm/helm#8094](https://github.com/helm/helm/issues/8094) I mentioned

<img width="1511" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/21bafa1a-f92f-4d87-8776-fe5dd7655b23">
No effect, unable to update repository

**Comment by clcc2019** [comment]
> If you add repository directly via Helm CLI - does it work?

Yes, I added the warehouse with helm in advance on my mac command line, and the dashboard can be used normally

**Comment by undera** [comment]
Is there some public ACR repo URL that I can use to reproduce this issue?

**Comment by clcc2019** [comment]
> Is there some public ACR repo URL that I can use to reproduce this issue?

I don't have a public warehouse to provide
<img width="1506" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/c15f8009-87b6-4d4e-9433-2cdd0c7de0f1">

**Comment by undera** [comment]
I don't find any mention of "acr" protocol in Helm source code, only "oci". When you say `Yes, I added the warehouse with helm in advance on my mac command line, and the dashboard can be used normally` - which command did you run? Was it `helm repo add ...` or something else?

**Comment by undera** [comment]
I'm a bit confused how did you add that "acr" to your helm repository list. Helm source code clearly does not allow that, from my knowledge. If you changed the repo list JSON file manually - that's something different.

Helm dashboard uses Helm source code to manage repositories, so if it fails - the Helm CLI should also fail.

It's hard to investigate this issue further without reproducible example, sorry.

**Comment by clcc2019** [comment]
> I'm a bit confused how did you add that "acr" to your helm repository list. Helm source code clearly does not allow that, from my knowledge. If you changed the repo list JSON file manually - that's something different.
> 
> Helm dashboard uses Helm source code to manage repositories, so if it fails - the Helm CLI should also fail.
> 
> It's hard to investigate this issue further without reproducible example, sorry.

What is the helm version used by the dashboard? Less than v3.8.0 does not support oci by default

**Comment by clcc2019** [comment]
https://github.com/helm/helm/issues/10892

**Comment by clcc2019** [comment]
helm supports oci, but helm-dashboard does not seem to support it yet

<img width="854" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/bcd50cf0-84b0-429a-a0ef-084b29a67ebf">

**Comment by clcc2019** [comment]
helm
<img width="1504" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/e0f28662-c309-4fee-b330-ea138215d4fd">

**Comment by undera** [comment]
Here is corresponding line in helm-dashboard: https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/objects/repos.go#L116

You can see that it indeed calls the Helm's source code from it. We use recent versions of Helm, like 3.11, so the OCI support is there for sure.

Since you never showed your actual command to add repo, I assume you are using some non-helm way to add that repo, like editing files directly.

I'm overall quite confused what is the problem, and don't see how and what can I improve in dashboard to help your case.
