### ISSUE TITLE
addRepo button didn't refresh when this action returned 500

### ISSUE THREAD

**Issue by spwangxp** [komodorio/helm-dashboard#362]
### Description

when add repo, the server returned `500` error,  but the button not refreshed even switch tab, unless force refresh site page.

### Screenshots

![image](https://github.com/komodorio/helm-dashboard/assets/24298044/1864b17f-531c-4e67-a936-1124e54d50e7)

**Comment by harshit-mehtaa** [comment]
can you please add Helm-Dashboard version being used, env config and other details needed to debug the issue

**Comment by warjiang** [comment]
helm-dashboard use helm pkg to handle repo metadata, but helm only supported to push/pull charts from oci registry, if you use artifacthub.io as repo, helm will try to visit artifacthub.io/index.yaml, and it will return 404, so configuration of artifacthub will be failed.


you can refer this link: https://github.com/helm/helm/issues/12538


if you want to use helm dashboard to manage your chart, you can use chartmuseum as a self hosted chart repo, or use standard repo, which means you can visit `{repo}/index.yaml` directly, such as `https://charts.bitnami.com/bitnami`

**Comment by warjiang** [comment]
it seems that helm will not support oci registry very quickly, will helm-dashboard willing to add feature to support third party oci registry, for example arrtifacthub provide api to list charts: https://artifacthub.io/docs/api/, meanwhile many cloud provider also provide sdk to list chart inside oci registry.
