### ISSUE TITLE
Build Docker image for ARM64

### ISSUE THREAD

**Issue by Jufik** [komodorio/helm-dashboard#365]
### Description

Currently, using image based on existing helm/docker image on ARM64 based servers, 
workload doesn't fire up with an `exec format error` message.

### Screenshots

<img width="1342" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/4503722/9b643e4f-0526-4939-86cf-988223988772">

**Comment by undera** [comment]
Hi @Jufik 
The image releasing flow lives here: https://github.com/komodorio/helm-dashboard/blob/main/.github/workflows/release.yaml#L51

If you know the way to add ARM image releasing to, I'll be happy to accept the contribution

**Comment by undera** [comment]
I found this doc: https://docs.docker.com/build/ci/github-actions/multi-platform/
Trying to apply it to our case

**Comment by undera** [comment]
@Jufik I have made a new release with this change. Please let me know if it works now for you.

**Comment by zentavr** [comment]
I still have `exec format error` with Arm image.

**Comment by zentavr** [comment]
Could the issue be here: https://github.com/komodorio/helm-dashboard/blob/main/Dockerfile#L6

**Comment by zentavr** [comment]
@undera Probably we should have `GOARCH` as `arm64` when we building for ARM64 and `amd64` when we do for x86_64. We can use `ARG GOARCH=amd64` instead of `ENV GOARCH=amd64`

**Comment by undera** [comment]
@zentavr Can you try changine that one line, building image and running it? I want to make sure that it is sufficient

**Comment by zentavr** [comment]
Hello @undera.

I think I can, but I’m not too much familiar with GitHub actions.

As I understood, I need to make a fork and try, correct?

**Comment by undera** [comment]
No, I meant checking out source code, modifying one line and doing image building and then trying to run it. Assuming all done on ARM machine

**Comment by zentavr** [comment]
I have ARM servers in AWS and Hetzner, so I can try it out.

**Comment by undera** [comment]
@zentavr I've also uploaded a test image without amd64 set. Can you try running `docker run -it komodorio/helm-dashboard:undera --help` to see if it is correct now?

**Comment by zentavr** [comment]
There is a [good example](https://actuated.dev/blog/multi-arch-docker-github-actions) how to implement the feature with GitHub actions. You can add an image for raspberry pi as well

**Comment by zentavr** [comment]
...Submitting the PR

**Comment by undera** [comment]
I've did what is written in that article. Let's see if it works for you. Should upload as `komodorio/helm-dashboard:unstable`

**Comment by zentavr** [comment]
@undera: Here is an output for `unstable` image:
```
root@arm64:~# docker run -it --entrypoint /bin/sh komodorio/helm-dashboard:unstable
Unable to find image 'komodorio/helm-dashboard:unstable' locally
unstable: Pulling from komodorio/helm-dashboard
8c6d1654570f: Already exists
c19f751c7db7: Pull complete
72878fe0e70c: Pull complete
4f4fb700ef54: Pull complete
60b38cbd5c7c: Pull complete
59c4bb683427: Pull complete
Digest: sha256:a38345a56dff7de538e6e2856a398007a6cb4f3f99ba9717dfe4097cbe265fd0
Status: Downloaded newer image for komodorio/helm-dashboard:unstable
/ # ldd /bin/helm-dashboard
/lib/ld-musl-aarch64.so.1: /bin/helm-dashboard: Not a valid dynamic program
/ # /bin/helm-dashboard --help
/bin/helm-dashboard: line 1: syntax error: unexpected ")"
/ # /bin/helm-dashboard --help
/bin/helm-dashboard: line 1: syntax error: unexpected ")"
```

**Comment by zentavr** [comment]
`--help` test exits with this:
```
root@arm64:~# docker run -it komodorio/helm-dashboard:unstable --help
exec /bin/helm-dashboard: exec format error
```

**Comment by undera** [comment]
The build with latest changes has not finished yet: https://github.com/komodorio/helm-dashboard/actions/runs/5323755070/jobs/9642059330

**Comment by undera** [comment]
Now it has built. Please try testing again, don't forget to do `docker pull` to get fresh image

**Comment by zentavr** [comment]
@undera which image should I try out?

**Comment by zentavr** [comment]
@undera: tried the image once again:
```
root@arm64:~# docker run -it komodorio/helm-dashboard:unstable --help
Unable to find image 'komodorio/helm-dashboard:unstable' locally
unstable: Pulling from komodorio/helm-dashboard
8c6d1654570f: Already exists
f5b226a9665a: Pull complete
98355d00be18: Pull complete
4f4fb700ef54: Pull complete
73e5fb20530f: Pull complete
739f21115177: Pull complete
Digest: sha256:893fcbc0490dbb96074e1ce5a608aa65f08607714d66db600a7cf072c4b78c9b
Status: Downloaded newer image for komodorio/helm-dashboard:unstable
Usage:
  helm-dashboard [OPTIONS]

Application Options:
      --version       Show tool version
  -v, --verbose       Show verbose debug information
  -b, --no-browser    Do not attempt to open Web browser upon start
      --no-analytics  Disable user analytics (Heap, DataDog etc.)
      --bind=         Host binding to start server (default: localhost)
  -p, --port=         Port to start server on (default: 8080)
  -n, --namespace=    Namespace for HELM operations
      --devel         Include development versions of charts
      --local-chart=  Specify location of local chart to include into UI

Help Options:
  -h, --help          Show this help message
```

Seems like it had been fixed.
`docker inspect` says it's only:
```
        "Architecture": "arm64",
        "Os": "linux",
```

**Comment by undera** [comment]
Is this image sufficient for your needs @zentavr ? I don't want to add other ARM variants for now, due to very long build times.

**Comment by zentavr** [comment]
That arm should work in AWS as well. I will try that later

**Comment by zentavr** [comment]
@undera Tried in AWS with `t4g.xlarge`:
```
root@ip-172-31-67-75:~# docker run -it komodorio/helm-dashboard:unstable --help
Unable to find image 'komodorio/helm-dashboard:unstable' locally
unstable: Pulling from komodorio/helm-dashboard
8c6d1654570f: Pull complete
f5b226a9665a: Pull complete
98355d00be18: Pull complete
4f4fb700ef54: Pull complete
73e5fb20530f: Pull complete
739f21115177: Pull complete
Digest: sha256:893fcbc0490dbb96074e1ce5a608aa65f08607714d66db600a7cf072c4b78c9b
Status: Downloaded newer image for komodorio/helm-dashboard:unstable
Usage:
  helm-dashboard [OPTIONS]

Application Options:
      --version       Show tool version
  -v, --verbose       Show verbose debug information
  -b, --no-browser    Do not attempt to open Web browser upon start
      --no-analytics  Disable user analytics (Heap, DataDog etc.)
      --bind=         Host binding to start server (default: localhost)
  -p, --port=         Port to start server on (default: 8080)
  -n, --namespace=    Namespace for HELM operations
      --devel         Include development versions of charts
      --local-chart=  Specify location of local chart to include into UI

Help Options:
  -h, --help          Show this help message

root@ip-172-31-67-75:~# uname -a
Linux ip-172-31-67-75 5.15.0-1023-aws #27-Ubuntu SMP Thu Oct 20 16:46:19 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

Processor:
```
Processor Information
	Socket Designation: CPU00
	Type: Central Processor
	Family: ARMv8
	Manufacturer: AWS
	ID: C1 D0 3F 41 00 00 00 00
	Signature: Implementor 0x41, Variant 0x3, Architecture 15, Part 0xd0c, Revision 1
	Version: AWS Graviton2
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: 2500 MHz
	Current Speed: 2500 MHz
	Status: Populated, Enabled
	Upgrade: None
	L1 Cache Handle: Not Provided
	L2 Cache Handle: Not Provided
	L3 Cache Handle: Not Provided
	Serial Number: AWS Graviton2
	Asset Tag: AWS Graviton2
	Part Number: AWS Graviton2
	Core Count: 4
	Core Enabled: 4
	Thread Count: 4
	Characteristics: None
```

**Comment by undera** [comment]
Works now, v 1.3.3+
