### ISSUE TITLE
Helm releases with different "storage" vs "install" namespace

### ISSUE THREAD

**Issue by mjnagel** [komodorio/helm-dashboard#37]
When managing a helm chart via [Flux](https://github.com/fluxcd/flux2) a `HelmRelease` custom resource is created with a given `storageNamespace` (`foo`), but could have a different `targetNamespace` (`bar`) which determines where the chart is installed (ref the [spec here](https://fluxcd.io/flux/components/helm/helmreleases/#specification)). The net result is that helm secrets, etc will be stored in the `foo` namespace, but `bar` is the "release namespace" where the chart is installed.

The logic handling of helm "lookups" by the dashboard seems to be problematic in this scenario. See the below example:
```console
> helm ls -n foo
NAME                         	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                     	APP VERSION
bizbang                      	bar       	1       	2022-10-24 14:16:07.803938 -0600 MDT   	deployed	bizbang-1.45.0
```
From this helm command you can see that the namespace scope of the `helm ls` command is `foo` (my Flux `storageNamespace`), but the namespace listed here is `bar` (my Flux `targetNamespace`).

When I try to click on this in the dashboard I receive the error "Failed to get chart details Error: release: not found". Looking at my terminal I can see it is using the wrong namespace in the lookup:
```console
WARN[1087] Failed command: [helm history bizbang --namespace bar --output json --max 18 --kube-context <removed>] 
WARN[1087] STDERR:
Error: release: not found
```
Using the `foo` namespace the `helm history` command would make this work. 

It would be great to see this scenario supported/handled, although I understand if its seen as an unsupported edge case.

**Comment by mjnagel** [comment]
> I would like to understand the issue more. The way dashboard queries the initial list of charts is by running `helm ls --all-namespaces --output json`. In the results JSON, I see only one `namespace` field that I'm able to use for further lookups. There is no "storage namespace" information available.

That's a great point - the "storage namespace" information isn't visible in this output. My understanding is that the concept of "storage namespace" might be unique to Flux.

Your proposed solution of `HD_STORAGE_NAMESPACE` would work only if it is used for all `helm` commands as the namespace. For example, when running the `helm history bizbang` command you would need to use `--namespace $HD_STORAGE_NAMESPACE` rather than the namespace returned by `helm ls`. This would also assume that the "storage namespace" is the same for all helm charts, which may not be the case.

> Does this approach mean there cannot be the same chart installed into 2 different namespaces under the same release name?

I'm not sure I totally follow this question, but you should still be able to install the same chart in 2 namespaces - you may just need to place them in 2 separate storage namespaces as well.

After looking at it further the best (maybe only?) way I can think of to grab the "storage namespace" dynamically would be through helm secret lookups. If you were to run `kubectl get secret -A --field-selector type=helm.sh/release.v1` this would display the correct namespace to use for further lookups. Example:
```console
> k get secret -A --field-selector type=helm.sh/release.v1
NAMESPACE   NAME                                                  TYPE                 DATA   AGE
foo         sh.helm.release.v1.bizbang.v1                         helm.sh/release.v1   1      127m
```
The result of this query would inform other `helm` commands, i.e. to grab the history for the given helm release you would run `helm history bizbang -n foo`. I'm not sure if querying secrets is something you'd want to get into with the code but that might be the only way to handle this dynamically.

**Comment by undera** [comment]
Thanks for the clarifications. 
I would not like to parse raw Helm information from secrets, I'd rather rely on some standard queries via Helm.

If it's acceptable to say that with `HD_STORAGE_NAMESPACE` env variable the dashboard becomes limited to a specific namespace, that's easy to implement. Though it would mean the new chart install and upgrade will also be limited to that namespace. I'm not sure there won't be any conflicts between how Flux does it and original Helm does it.

Again, we can experiment, the cost of it is relatively low.

**Comment by mjnagel** [comment]
> I would not like to parse raw Helm information from secrets, I'd rather rely on some standard queries via Helm.

That's understandable. For clarification though you could use standard helm commands and lookups for everything except getting the initial list of helm releases/namespaces. Any time you need the list of helm installs plus their namespaces you would have to grab from the secret, everything else could be done with helm commands once you have the name and namespace.

The suggested `HD_STORAGE_NAMESPACE` env is probably an easy add that gives some functionality now. You're probably correct that the way Flux implements it's helm controller may deviate from a standard helm install in tiher ways too.

**Comment by undera** [comment]
Some improvements been done. Let's revisit this if necessary

**Comment by antonosmond** [comment]
Apologies for digging up an old issue but was this ever resolved? AFAICT, there's no support for a storage namespace.
I have the same issue as the OP, I'm using [flux](https://fluxcd.io/flux/) which in turn uses helm and the storage namespace and target namespace for the releases are different. Here's the output of `helm ls -n flux-system` (note `flux-system` is the storage namespace):

```
NAME                    	NAMESPACE       	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
external-secrets        	external-secrets	5       	2024-09-13 13:06:13.604736658 +0000 UTC	deployed	external-secrets-0.24.0        	0.6.0-rc1
fluent-bit              	monitoring      	1       	2024-09-09 15:24:09.53700246 +0000 UTC 	deployed	fluent-bit-0.0.1               	3.1.4
kube-state-metrics      	monitoring      	2       	2024-09-17 13:43:15.974020499 +0000 UTC	deployed	kube-state-metrics-0.16.0      	2.12.0
metrics-server          	kube-system     	1       	2024-09-16 14:42:04.546843819 +0000 UTC	deployed	metrics-server-3.12.1          	0.7.1
opentelemetry-collector 	monitoring      	4       	2024-09-17 18:20:50.080780692 +0000 UTC	deployed	opentelemetry-collector-0.117.0	0.90.1
podinfo                 	default         	1       	2024-09-16 14:42:04.325367974 +0000 UTC	deployed	podinfo-6.5.4                  	6.5.4
prometheus              	monitoring      	2       	2024-09-16 10:15:07.682640798 +0000 UTC	deployed	prometheus-0.92.1              	2.37.8
prometheus-node-exporter	monitoring      	1       	2024-09-09 15:24:52.875996145 +0000 UTC	deployed	node-exporter-0.5.0            	1.0.0
storage-classes         	flux-system     	1       	2024-09-09 15:24:10.410735213 +0000 UTC	deployed	storage-0.3.1                  	1.16.0
```

If I open helm dashboard with the namespace set to `flux-system`, I can see only the `storage-classes` release. I assume this is because the storage namespace (`flux-system`) and the target namespace (also `flux-system`) are the same for this release. For all other releases, the target namespace is different. If I set the namespace on the helm dashboard command to one of my target namespaces e.g. `helm dashboard -n monitoring`, I don't see any of the releases. I assume because the secrets that track the helm releases are created in the storage namespace and not the target namespace.

It would would be super handy if there was a way to configure the storage namespace, like the original suggestion of an env var.

It's probably also worth saying that someone using another tool to manage helm releases probably only wants a read-only view in the dashboard i.e. I wouldn't want to install or modify a release via helm-dashboard as this would conflict with my flux configurations. Given a read-only view would probably only use `helm ls`, it may address the point raised by @undera i.e.

> I see that I could satisfy your use-case, say, with env variable HD_STORAGE_NAMESPACE, that would replace --all-namespaces if present. While I see how it works for the initial helm ls, how would it work for further commands?

In the case of a read-only view, it wouldn't need to work for further commands.

**Comment by undera** [comment]
@antonosmond This particular issue was addressed with some code changes in the past. What you write in your message is probably new (or better explained) issue. To not revive and drag old and rotten issue, I kindly ask you to open a new issue with your observations (nicely explained BTW, thanks for that).

The code probably needs some more change to support storage namespace properly.
