### ISSUE TITLE
Query deployment is slow

### ISSUE THREAD

**Issue by clcc2019** [komodorio/helm-dashboard#396]
### Description

<img width="1504" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/e03def14-94cf-48db-bce9-db5ee6d5e6e1">
<img width="1503" alt="image" src="https://github.com/komodorio/helm-dashboard/assets/46099295/f40eeedb-17d9-4a4c-97d6-e377abd59cbb">
I have many release and it is slow to query the details of a particular release

**Comment by undera** [comment]
Hi

To help you, I'll need a bit more details on what happens.

Can you do following experiment: 
  1. open the page with single release, just like on screenshots above
  2. restart helm-dashboard process, without closing browser tab
  3. Refresh browser page, to make sure it loads only that page

I would expect that page to load fast enough. What will be your experience?
