### ISSUE TITLE
Check for new version upon start

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#43]
Query GH API, compare with current version, offer to upgrade

**Comment by ahaw023** [comment]
this would be good in the overview UI as an upgrade available icon. 

This would let users quickly identify which charts to review and update

![image](https://user-images.githubusercontent.com/106289240/198511810-9c584add-9c20-4ddc-9959-6c6dd69705dc.png)

**Comment by undera** [comment]
This was about Helm Dahsboard itself, and is already implemented.

As for helm chart repository updates, I am still not sure if it would be right to automatically update all the repos. Wouldn't it be sometimes undesired @ahaw023 ?
