### ISSUE TITLE
Improve revision block for long numbers

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#468]
When it's thousands of revisions, the display is a bit off. We need to wrap it into block somehow.

![Selection_004](https://github.com/komodorio/helm-dashboard/assets/2026469/6ea3220f-9975-4a8d-9cf6-a4c1881a5ec7)

**Comment by SD007CSE** [comment]
Hello, @undera can you help me to reproduce the issue?

**Comment by undera** [comment]
> Hello, @undera can you help me to reproduce the issue?

The easiest way to reproduce would be to patch the frontend or backend to artificially increase revision numbers. 

In backend, it can be done in this line: https://github.com/komodorio/helm-dashboard/blob/helm-dashboard-v2/pkg/dashboard/handlers/helmHandlers.go#L701 by adding `+1000` to revision value.

In frontend, you can do it by adding `+1000` to revision number here: https://github.com/komodorio/helm-dashboard/blob/helm-dashboard-v2/dashboard/src/components/revision/RevisionsList.tsx#L52

Please note that we currently work in v2 branch, which should be merged in main soon.

**Comment by harshit-mehtaa** [comment]
is the v2 branch private because i am unable to view it?

**Comment by undera** [comment]
We've just merged V2 to main, so now all PRs are from main branch again @harshit-mehtaa
