### ISSUE TITLE
Namespace support for helm-dashboard

### ISSUE THREAD

**Issue by hdm23061993** [komodorio/helm-dashboard#48]
I was trying to access a k8s cluster where I have access to only a single namespace, but when I tried to run `helm dashboard` command from CLI on that k8s cluster it gave me an error as it's trying to scan all the namespaces which i don't have access to

```
WARN[0018] helm ls --all --all-namespaces --output json --time-format 2006-01-02T15:04:05Z07:00 --kube-context xxxxx
WARN[0018] STDERR:
Error: list: failed to list: secrets is forbidden: User "zzzz" cannot list resource "secrets" in API group "" at the cluster scope
```

I would suggest having 2 features here which would be very useful
1. A parameter to set the default namespace which can be used on startup and other operations
2. Ability to switch namespace from the UI (if the user has access to multiple namespaces on the k8s cluster)

**Comment by undera** [comment]
Relates to #37

**Comment by ahaw023** [comment]
a short work around would be to use kubens and kubectx to configure the right namespace prior to running the command

if you go to http://localhost:8080/api/kube/contexts you would see what your kubectl configs currently look like
