### ISSUE TITLE
options for auth / api key for backend routes

### ISSUE THREAD

**Issue by aimenhamed** [komodorio/helm-dashboard#485]
Hey,

I think it'll be really good to have an option to protect the API routes from the Go server with auth or maybe by an api key? Looking to leverage the dashboard but wanting to protect the potentially dangerous operations (like delete or rollback) so that only a service or user with an API key can access them. For more context I am deploying this with the helm chart, would be good to have as an option in the chart which gets passed to the service.

Thanks!

**Comment by undera** [comment]
@aimenhamed 
To achieve that, you have 2 options: use [Authentication Proxy](https://github.com/oauth2-proxy/oauth2-proxy) service, or use Komodor platform freemium. Komodor comes with RBAC and teamwork features out-of-the-box.

I don't see the point in redoing what Google did with authentication proxy, seems like duplication of effort.

**Comment by aimenhamed** [comment]
oh ok thank you !
