### ISSUE TITLE
long helm charts are going too out of the box 

### ISSUE THREAD

**Issue by soumdatta81** [komodorio/helm-dashboard#49]
While displaying the helm chart in the helm dashboard long chart goes out of the box.
Here is a screenshot of the issue: https://imgur.com/a/Is8j0Ry

**Comment by undera** [comment]
Thanks. This is supposed to be fixed with https://github.com/komodorio/helm-dashboard/commit/2262445b7574497de3b2eea4ec30da25110dda0b
