### ISSUE TITLE
download or scroll button for scan reports

### ISSUE THREAD

**Issue by soumdatta81** [komodorio/helm-dashboard#50]
After doing a particular scan the report is incomplete and cant be scrolled. A download button to download the complete scan or maybe a scrollable button will be helpful.

**Comment by undera** [comment]
Can you provide a screenshot where you could not scroll it?

**Comment by ahaw023** [comment]
@soumdatta81  browsing to http://localhost:8080/api/helm/charts will giver you a JSON representation of the charts installed
you will need to set a x-kubecontext: header if you have multiple kubectl context

you can list the context form a helm-dashboard point of view by browsing to

http://localhost:8080/api/kube/contexts

**Comment by undera** [comment]
I see scrolls for scan results. Closing this as invalid
