### ISSUE TITLE
trying to check artifacts on ArtifactHub

### ISSUE THREAD

**Issue by jainpratik163** [komodorio/helm-dashboard#506]
### Description

I tried to install helm dashboard as helm chart on EKS and in logs I see below msg `Failed to query ArtifactHub`

```
[GIN] 2024/01/28 - 11:24:14 | 204 |         1m29s |   100.126.5.139 | GET      "/api/helm/repositories/latestver?name=my-chart"
time="2024-01-28T11:24:14Z" level=warning msg="Failed to query ArtifactHub: Get \"https://artifacthub.io/api/v1/packages/search?offset=0&limit=5&facets=false&kind=0&deprecated=false&sort=relevance&ts_query_web=my-chart\": dial tcp 99.86.229.58:443: i/o timeout"
t
```
and because of this ingress is also performing very slowly how can we disable this check?

and also for now it is showing all the namespaces that we can restrict to a few ns.

**Comment by undera** [comment]
Disabling ArtifactHub query is something that needs development. I guess an environment variable would be sufficient.

As for namespace limitations, we have a CLI flag to limit dashboard to certain set of namespaces. Have you tried setting that?

**Comment by jainpratik163** [comment]
@undera i am trying to install this via helm chart and in helm chart how I can use the CLI flag as you mentioned, nothing is mentioned as such.
could you please help with this.

**Comment by undera** [comment]
@jainpratik163 To have this as part of Helm registry, we'd need to release version 2.0. We are not quite ready for that. 
For now, you can try to build it locally with `make build`, or to set "unstable" image via Helm values, has good chance to work:
```
image:
    tag: unstable
```
