### ISSUE TITLE
Respect default namespace from kubectl config while installing

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#51]
Right now it is hardcoded as "default". We have an optional default namespace coming from context information. We should use that (if present) as namespace when installing new chart.
In case there is forced namespace set, use it instead.

**Comment by hdm23061993** [comment]
I see that this logic already exists

https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/static/actions.js#L132
```javascript
const ns = $("#upgradeModal .rel-ns").val();
setHashParam("namespace", ns ? ns : "default")
```

Also, while testing locally I observed that the forced namespace feature is already working
![image](https://user-images.githubusercontent.com/17697790/200568167-6084d710-d7b0-41cd-addf-27d900bd6e24.png)



Could you please add more information?

**Comment by undera** [comment]
The issue is actually about different thing. 
When you have a namespace configured for a context in your kubectl config file, this setting should be respected at least in the "Install new chart" dialog.
