### ISSUE TITLE
Does not read system proxy

### ISSUE THREAD

**Issue by sino1641** [komodorio/helm-dashboard#530]
### Description

My host is using http proxy to access the Internet.
```
export HTTP_PROXY="http://ip:port"
export HTTPS_PROXY="http://ip:port"
```
But helm dashboard is not reading it:
```
DEBU[0541] Error: Get "https://github.com/example.tgz": dial tcp 20.205.243.166:443: connect: connection timed out 
```

I can download the chart using:
```
curl https://github.com/example.tgz -x ip:port
```
Plz guide, thanks.

**Comment by undera** [comment]
Hello
When I configure environment variables, all works for me as expected. Exported env vars might not pass through some of the shell wrappers.
I suggest you trying to specify env variables more directly like `HTTP_PROXY="http://ip:port" HTTPS_PROXY="http://ip:port" ./helm-dashboard`

**Comment by sino1641** [comment]
Hi and thanks! It works per your guidance.
