### ISSUE TITLE
Embed resources loaded from CDN

### ISSUE THREAD

**Issue by murphy85** [komodorio/helm-dashboard#541]
### Description

We are in a closed environment and don't have access to all resources in the internet. There are some resources that should be loaded from CDN servers, but they cannot be resolved. 
There already was an issue regarding this topic: #498 
This should be solved in version 2.x. When will this be available?
We tried the latest versions (helm plugin and binary)

INFO[0000] Helm Dashboard by Komodor, version 1.3.3 (b61adf133f639b8bffd43925b5b4b8230c197a26 @ 2023-06-22T08:59:05Z) 

### Screenshots

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/e7f55b8e-bebe-4e8f-81e7-36ba1767e442">

**Comment by undera** [comment]
Hello @murphy85 
Version 2.0 is yet to be released. You can help that process by building it locally from sources and testing that it functions in your closed environment.
Just run `make build && make debug` in the sources directory.

**Comment by murphy85** [comment]
I would like to help that process, but unfortunately npm and network connection to npm repositories are not available on that machines. I tried to convince our admins with no success. I will try to find a similar machine with permissions.
