### ISSUE TITLE
Query helm chart source for icon and description

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#55]
In the list of installed charts, attempt to improve display by issuing additional call to query for icon and description. 
This would require introducing a new API call, since we don't want to delay the display of the list. This needs to match release to repository, which we already able to do.
Then, `helm show chart komodorio/k8s-watcher` to get the icon URL and description. 
Make sure the UI is not "jumping" because of variable description length.

**Comment by hdm23061993** [comment]
I would like to pick this up

**Comment by undera** [comment]
Go for it

**Comment by hdm23061993** [comment]
`helm show chart` gives response back in yaml format
is there a way to fetch from yaml response or convert it to json?

**Comment by hdm23061993** [comment]
or is better to do it on go?

**Comment by undera** [comment]
Parsing the YAML is not too big of a problem. We already work with it like here: https://github.com/komodorio/helm-dashboard/blob/c0a1d31c8d717db1bf5d42ab84275aca3f988ade/pkg/dashboard/subproc/data.go#L269

In case of `helm show ...` it can be even simpler, since it's a single-document expected in output.
https://github.com/helm/helm/blob/main/pkg/chart/metadata.go#L47 should be the type into which it is deserialized, or something around it.

The data layer should do the responsibility of parsing this into objects.

**Comment by hdm23061993** [comment]
@undera 
Can you please cherry-pick the PR and see the API performance? What I observed is API call happens in the background. So once the home page (installed charts list) loads, it takes a while to populate the icon and description until the API execution completes.
Maybe there is a better way to handle that?
