### ISSUE TITLE
no dockerhub image for 2.0.2

### ISSUE THREAD

**Issue by seboudry** [komodorio/helm-dashboard#556]
### Description

Hi @undera!

Thanks for this new release!

Unfortunately, the 2.0.2 tag does not exist for the container image in Docker Hub (OCI Helm does).
https://hub.docker.com/r/komodorio/helm-dashboard/tags

**Comment by undera** [comment]
Hi
That image is intended to be used with Helm. I tested it with Helm and it worked for me. 
What do I miss? Do you need an image for the other purpose?

**Comment by seboudry** [comment]
We use an Harbor instance to proxy cache dockerhub (and also for security reasons).

So I got this on my Helm values:
```yaml
image:
  repository: harbor.quicksign.fr/dockerhub/komodorio/helm-dashboard
```

But even with a simple docker run, I got this error:
```shell
❯ docker run --rm -it harbor.mycompany.com/dockerhubproxy/komodorio/helm-dashboard:2.0.2
Unable to find image 'harbor.mycompany.com/dockerhubproxy/komodorio/helm-dashboard:2.0.2' locally
2.0.2: Pulling from dockerhubproxy/komodorio/helm-dashboard
docker: unsupported media type application/vnd.cncf.helm.config.v1+json.
```

Only the Helm chart is taged `2.0.2` on DockerHub.
The container image is well updated on `latest` tag but don't have `2.0.2` one

**Comment by undera** [comment]
Here is what I see:
```
undera@desktop:~$ docker run -it komodorio/helm-dashboard --version
2.0.2
```

Probably you need to refresh local image

**Comment by seboudry** [comment]
mmhhh I don't get any image locally

```shell
❯ docker image ls | grep helm
# nothing
❯ docker run --rm -it komodorio/helm-dashboard:2.0.2
Unable to find image 'komodorio/helm-dashboard:2.0.2' locally
2.0.2: Pulling from komodorio/helm-dashboard
docker: unsupported media type application/vnd.cncf.helm.config.v1+json.
See 'docker run --help'.
```

**Comment by bw-henry-he** [comment]
I get the container but it has an issue starting up 
```
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/helm-dashboard": stat /bin/helm-dashboard: no such file or directory: unknown 
```
I haven't changed the start command at all

**Comment by undera** [comment]
Can you use the "latest" image tag?

**Comment by undera** [comment]
Can somebody try with version 2.0.3? It should work now.

**Comment by unitmatrix** [comment]
I've tested pulling the image from Docker Hub with version 2.0.3 and it worked perfectly. Thanks for the update!
