### ISSUE TITLE
Helm Dashboard UI not accessible if cluster name contains slash

### ISSUE THREAD

**Issue by sunnyar** [komodorio/helm-dashboard#557]
### Description

Since I updated to the latest version, my helm dashboard UI has stopped working and I'm getting an error which I'm not able to understand.

It's giving a 500 error for the /api/helm/releases GET API call. But when I use the REST API calls through the swagger docs, it is working as expected. Also, not sure why is it not referencing to the default set cluster `arn:aws:eks:us-east-2:xxxxxxxxxxx:cluster/xyz-cluster`, instead just referring `arn:aws:eks:us-east-2:xxxxxxxxxxxxx:cluster`

Attaching screenshots for more reference

Can you please look into this issue and help. Thanks

### Screenshots

<img width="1214" alt="Screenshot 2024-11-14 at 10 18 24 AM" src="https://github.com/user-attachments/assets/eae344ba-e2b8-4498-a130-99b2fa9d5eb0">
<img width="1023" alt="Screenshot 2024-11-14 at 10 18 58 AM" src="https://github.com/user-attachments/assets/81c19a48-f8bc-4f27-9c58-9f22178f9bb9">
<img width="928" alt="Screenshot 2024-11-14 at 10 20 09 AM" src="https://github.com/user-attachments/assets/78213036-c0c2-4e3a-b5fa-fd54d9c9d9d1">

**Comment by undera** [comment]
Try erasing whatever you have in your URL from local experiments and start with clean URL.

**Comment by sunnyar** [comment]
I've tried that also. If I clean-up the url and just have `http://localhost:8080/` and enter, I observe two behaviours

1. It redirects to the url specifying one of the clusters installed, but still not the current one
http://localhost:8080/#/arn:aws:eks:us-east-2:xxxxxxxxxxxx:cluster/abc-cluster/installed

2. Still throws the same error as shown in the screenshots

Have also tried Reset Cache option, but no help

**Comment by undera** [comment]
The way it works inside is: it tries to get the default cluster from your kubeconfig, or takes the first one. 
In case it does not work, you can close the error message and choose different kubecontext from the left pane.

**Comment by undera** [comment]
Also mind the browser cache, which sometimes is a bit stubborn after change

**Comment by sunnyar** [comment]
I have tried clearing all cookies and cache, but nothing worked.
And when I close the error and select the clusters from the list of clusters on the left panel, only the url changes and nothing else happens. So stuck there also

**Comment by undera** [comment]
Fairly, I ran out of ideas what can be wrong there. Feel free to use older version if 2.x does not work for you.

**Comment by sunnyar** [comment]
Using [v1.3.3](https://github.com/komodorio/helm-dashboard/releases/download/v1.3.3/helm-dashboard_1.3.3_Darwin_arm64.tar.gz) binary, the issue no longer exists on my end and I'm able to see all the list of clusters in the expected manner.

**Comment by yuma-brendan** [comment]
I'm running into the same issue, and I think that the helm-dashboard isn't parsing the cluster name properly since there's a slash in it.

```
Error #01: failed to get list of releases, cause: Kubernetes cluster unreachable: context "arn:aws:eks:us-east-2:XXXXXXXXXX:cluster" does not exist
```


The correct context name is: `arn:aws:eks:us-east-2:XXXXXXXXXX:cluster/my-cluster`

**Comment by yuma-brendan** [comment]
Renaming the context fixes the issue.


`kubectl config rename-context arn:aws:eks:us-east-2:XXXXXXXXXX:cluster/my-cluster my-cluster`

**Comment by sunnyar** [comment]
> Renaming the context fixes the issue.
> 
> `kubectl config rename-context arn:aws:eks:us-east-2:XXXXXXXXXX:cluster/my-cluster my-cluster`

@yuma-brendan Thanks for the update. Will try this approach.

**Comment by undera** [comment]
This needs a fix, definitely

**Comment by sunnyar** [comment]
@unitmatrix @undera 

Installed the new version 2.0.3 with this fix available.

Getting the following issues again:

- Default cluster is still not been picked up

- Namespace filtering is not working as expected
(Selected main but the namespace columns shows both staging and main)
<img width="1389" alt="Screenshot 2024-12-04 at 9 05 32 AM" src="https://github.com/user-attachments/assets/87122d14-0363-43ba-b373-f39b1951b5ab">



- "Failed to get list of charts" issue again when selecting any of the charts
(http://localhost:8080/#/arn:aws:eks:xxxx:cluster/abc-cluster/staging/ui/installed/revision/7)
<img width="992" alt="Screenshot 2024-12-04 at 9 06 02 AM" src="https://github.com/user-attachments/assets/4a69b292-d0b6-4f18-a1af-8f8e20db0515">
