### ISSUE TITLE
Use k8s API programmatically instead of kubectl

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#56]
Use kubeconfig and appropriate env vars to figure out configuration, but don't require `kubectl` binary to be present, because Helm doesn't. Maybe even reuse API client that Helm has inside its codebase.

**Comment by markrity** [comment]
@undera from what I have seen `kubectl` only used to get list of all context at this function `ListContexts` . 

helm doesn't have listing all contexts functionality, tools like `kubectx` also use `kubectl` to parse the context (https://github.com/ahmetb/kubectx) 

If `kubectl` only used right now to get contexts and you really want to get rid of it, I can suggest parsing the `kubeconfig` manually. WDYT?

**Comment by undera** [comment]
`kubectl` is used to query: list contexts, describe the resource state and list of namespaces in #67

We can use kubectl functions as library, I already looked in the code that it's possible, this is the way I envision it. I would not like to copy all that code, if possible. kubectl code looks nice and clean and I'm optimistic we can just use it as library.
