### ISSUE TITLE
Privacy concerns with Datadog RUM.

### ISSUE THREAD

**Issue by matthewhembree** [komodorio/helm-dashboard#57]
Hello, I noticed that Datadog RUM is being used for application telemetry.

I didn't see any disclosures about that (including what's being tracked, how it's being used, how that data is secured). Not in the console (during installation and runtime), webUI, or in the README.md.

Additionally; IMO, it would be good to make this telemetry require an explicit opt-in. Some people, if they're comfortable, might be glad to provide telemetry. Others might conclude that your plugin is spyware. Some orgs may have strong objections to the values of the `name` and `namespace` query parameters being exposed as they may contain sensitive data.

I assume that you have good intentions and just want to ship performant and reliable software. 👍 

Even though I don't see any calls to `startSessionReplayRecording()`, It is good that you have  [defaultPrivacyLevel](defaultPrivacyLevel) as `mask`. It still would be courteous to see an explicit set of `sessionReplaySampleRate` to `0` as a failback safety mechanism.

**off-topic:** I do like the plugin! It's extremely useful.

Thanks!

**Comment by undera** [comment]
Thank you for reporting this concern and understanding what is important for the community. 
It will be addressed in #59
