### ISSUE TITLE
--help seems to be printing version instead

### ISSUE THREAD

**Issue by dmlond** [komodorio/helm-dashboard#63]
when I try to use `helm dashboard --help` on my system, it seems to print the version and exit.

```bash
$ helm dashboard --help
INFO[0000] Helm Dashboard by Komodor, version 0.2.3 (549cdd9bfbdf32009f8dbbc240c59c86c2e430d7 @ 2022-10-26T14:27:14Z)
```

I am on Ubuntu Jammy Jellyfish, using helm 3.10.1

**Comment by undera** [comment]
It's a confusion I've created by changing README into upcoming release variant. I've already created `v0.2.4` release, use it to get the right version.
