### ISSUE TITLE
Running on non-default port

### ISSUE THREAD

**Issue by mgauthier** [komodorio/helm-dashboard#65]
`helm dashboard --port 9999
INFO[0000] Helm Dashboard by Komodor, version 0.2.3 (549cdd9bfbdf32009f8dbbc240c59c86c2e430d7 @ 2022-10-26T14:27:14Z)`

When it’s running you get more output and it tells you something along the lines of, “Running on localhost:9999”, but I cannot access the dashboard itself, see below.

<img width="1168" alt="Screen Shot 2022-10-31 at 2 11 18 PM" src="https://user-images.githubusercontent.com/484724/199079862-70d3bd0d-fbeb-4d1d-8e9d-3d6fe396d596.png">

Any help would be appreciated

**Comment by undera** [comment]
Try upgrading to 0.2.4, because similar problem were fixed in that version
