### ISSUE TITLE
Hot reload for development

### ISSUE THREAD

**Issue by Wyfy0107** [komodorio/helm-dashboard#66]
It would be great if dev server can detect changes in `static` and refresh the UI

**Comment by undera** [comment]
I'm open to suggestions. How would you do that? Wouldn't it be annoying, 'cause not every change I do to sources implies my will to reload?

**Comment by suhaibaffan** [comment]
Can we have a proper development env using docker compose?
I don't want to install the plugin on my local, instead install on a docker container.

Later the same compose file can be used to run on test pipeline.

**Comment by undera** [comment]
When developing, you don't need to install anything. The plugin is a mere binary file, which is runnable via your IDE as-is.
There is special clause in the code to enable dynamic loading of frontend resources: https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/api.go#L116

I'm not sure how and when to reload the Golang backend. I usually just hit "restart" in my IDE once the next chunk of backend code is ready. When I change the frontend, I just refresh my browser page.

I don't see what would be the benefit of docker compose here, you are free to demonstrate it.

The original idea for this project is to not require any heavy installation and infrastructure. There are already good number of existing solutions that are installable into cluster.

**Comment by suhaibaffan** [comment]
I think my question for docker compose on this issue has caused some confusion. 
Thank you for the details though. 

To try out the helm dashboard I actually wanted to run it on a container in which a working kubectl and helm installed with the dashboard plugin. Which can be used to connect my docker desktop kube cluster or any remote cluster. This way I don't have to install kubectl and helm on local.

**Comment by undera** [comment]
Version 1.0 (#147) addresses this, also the dockerization has happened for the project
