### ISSUE TITLE
how to change default bind localhost to 0.0.0.0

### ISSUE THREAD

**Issue by JabinSun** [komodorio/helm-dashboard#69]
By default, the web server is only available locally. You can change that by specifying HD_BIND environment variable to the desired value. For example, 0.0.0.0 would bind to all IPv4 addresses or [::0] would be all IPv6 addresses.

so,how i use this HD_BIND to change localhost:8080,i cant find any answer

**Comment by undera** [comment]
The way depends on the OS or platform you use to run it. For example, in Linux you can just do it like this:
```shell
HD_BIND=0.0.0.0 helm dashboard
```

**Comment by JabinSun** [comment]
> ```shell
> HD_BIND=0.0.0.0
> ```
well, great, thanks

**Comment by JabinSun** [comment]
great, thanks

**Comment by JabinSun** [comment]
> The way depends on the OS or platform you use to run it. For example, in Linux you can just do it like this:
> 
> ```shell
> HD_BIND=0.0.0.0 helm dashboard
> ```

great, thanks
