### ISSUE TITLE
Fix getCleanClusterName to be more reliable

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#76]
The function should be safe to run on any cluster name. Currently, there are errors like
`clusterSplit.at is not a function. (In 'clusterSplit.at(-1)', 'clusterSplit.at' is undefined` on some cluster names.

**Comment by siddhikhapare** [comment]
@undera  I want to work on this issue.

**Comment by undera** [comment]
Go for it @siddhikhapare , it's a really tiny fix
