### ISSUE TITLE
Make items on Installed charts page to be correct hyperlinks

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#81]
To be able to open releases in a new browser tab, intuitively.

Installed charts in list should be correct links, and full row should be a link, not just header text.

Top menu items Installed/Repository should be correct links.

Revision links on the left should be correct links.

**Comment by undera** [comment]
@ahaw023 this is from your feedback, thanks for your exciting demos

**Comment by hdm23061993** [comment]
@undera can you please add more details for the below 2 items?

- Top menu items Installed/Repository should be correct links.
- Revision links on the left should be correct links.

**Comment by undera** [comment]
We have a top menu items "Installed" and "Repository". Those are now not hyperlinks, and handled on JS side. Those should become valid hyperlinks, so I'm able to do right click on those and choose "Open in new tab".

Same kind of behavior is expected for items in Installed list and in Revision list.
