### ISSUE TITLE
Chart icon disappears when chart description appears 

### ISSUE THREAD

**Issue by ronahk** [komodorio/helm-dashboard#90]
![D4334B57-FFD2-41EA-A618-AFF604F110DF_4_5005_c](https://user-images.githubusercontent.com/74967920/201154917-b2a5f9af-04ba-43e5-9243-e7230d227626.jpeg)

**Comment by undera** [comment]
Can this be because the Airflow icon is all white, and it is "white-on-white"?

**Comment by undera** [comment]
It's actually because their chart (https://github.com/airflow-helm/charts/blob/main/charts/airflow/Chart.yaml) references a non-existing image.

**Comment by undera** [comment]
Closing as not real issue
