### ISSUE TITLE
The chart icon does not display for two releases of the same chart

### ISSUE THREAD

**Issue by undera** [komodorio/helm-dashboard#91]
![Selection_002](https://user-images.githubusercontent.com/2026469/201161855-61c7b1b1-bc47-40d0-a2b4-cf6e1aed1f71.png)

Probably it takes the wrong field to find release's source. It should look at "chart" field, parse it to take only the name part and not version, and search it in the repositories. The release "name" is a wrong field to take.

I've overlooked that on the PR review here: https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/static/list-view.js#L32

**Comment by hdm23061993** [comment]
I can fix this.
Can you please assign it to me?
