### ISSUE TITLE
ChartAndVersion func may have wrong result in some case.

### ISSUE THREAD

**Issue by denganliang** [komodorio/helm-dashboard#95]
https://github.com/komodorio/helm-dashboard/blob/cf407c63a23e25cd15878661c2067458a14979b3/pkg/dashboard/utils/utils.go#L19

```
func ChartAndVersion(x string) (string, string, error) {
	lastInd := strings.LastIndex(x, "-")
	if lastInd < 0 {
		return "", "", errors.New("can't parse chart version string")
	}

	return x[:lastInd], x[lastInd+1:], nil
}
```

this func get the last index "-" of  the result of helm search repo or other command, 
it assume the last "-" seperate chartName and chartVersion ,
 but in my case it have the wrong result.

helm chart version  must be [SemVer 2](https://semver.org/) format,
 ref:  https://helm.sh/docs/chart_best_practices/conventions/#version-numbers

while  `1.2.3-alpha.1+123`  is a valid version for helm , ref  https://helm.sh/docs/chart_template_guide/function_list/#semver
```helm search repo xxx ```  return   ``` xxx-1.2.3-alpha.1+123```

in that case, if we use ```ChartAndVersion``` to get chartname and version ,  
 output is   ```xxx-1.2.3```  and ```alpha.1+123```
which is invalid.

i think this is a bug.

i have solution to fix it, i can push a merge request if needed.

**Comment by undera** [comment]
It is interesting how would you fix this. Feel free to create a  PR.

One important thing is this kind of functionality also exists in JS part of the app, and needs to be addressed, too.

**Comment by denganliang** [comment]
> It is interesting how would you fix this. Feel free to create a PR.
> 
> One important thing is this kind of functionality also exists in JS part of the app, and needs to be addressed, too.

I fix this func, I am not familiar with JS part of the app, can you point out where is also have this problems, So I can try to fix it?Or someone could help to fix the JS part.

**Comment by undera** [comment]
Currently I only find this place:  https://github.com/komodorio/helm-dashboard/blob/main/pkg/dashboard/static/list-view.js#L32

**Comment by hdm23061993** [comment]
@denganliang If needed, I can help handle the JS part

**Comment by denganliang** [comment]
> 
This nice, I  will only impove the Go Part.
